#include "common_dbc.h"

namespace {

const Signal sigs_168[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACCEL_RELATED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_257[] = {
    {
      .name = "ENERGY_OR_RPM",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_258[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "STEER_ANGLE",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 8,
      .size = 13,
      .is_signed = false,
      .factor = 0.3187251,
      .offset = -1307.888,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_RATE",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 24,
      .size = 13,
      .is_signed = false,
      .factor = 0.3187251,
      .offset = -1305.498,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_STEERING",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_264[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACCEL_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_268[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "BRAKE_PERHAPS",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_270[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACCEL_OR_RPM",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ELECTRIC_MOTOR",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_284[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "BRAKE_RELATED_1_1",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_RELATED_1_2",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_RELATED_1",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 40,
      .size = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_288[] = {
    {
      .name = "COUNTER",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 44,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACCEL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_ENGINE_RPM_MAYBE",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 32,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_291[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ENERGY_GAIN_LOSS",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENERGY_SMOOTHER_CURVE",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_294[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "UNKNOWN_126_1",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENERGY_GAIN_LOSS_NOISY",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 24,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNKNOWN_126_2",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_308[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_134",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 40,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_320[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "BRAKE_PRESSED_2",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSED_ACC",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_RELATED_2",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_324[] = {
    {
      .name = "SPEED_2",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 32,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_331[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "BRAKE_RELATED_3",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_332[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_2",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 11,
      .size = 13,
      .is_signed = false,
      .factor = 0.3187251,
      .offset = -1307.888,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENERGY_RELATED",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 40,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_344[] = {
    {
      .name = "WHEEL_SPEED_FL",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = false,
      .factor = 0.0189408,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 24,
      .size = 12,
      .is_signed = false,
      .factor = 0.0189408,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = false,
      .factor = 0.0189408,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 56,
      .size = 12,
      .is_signed = false,
      .factor = 0.0189408,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_384[] = {
    {
      .name = "NEW_SIGNAL_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_464[] = {
    {
      .name = "SEATBELT_DRIVER_UNLATCHED",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_500[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACC_STATUS_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 5,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_MAYBE",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_STATUS_2",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 19,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_BOOL_1",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_501[] = {
    {
      .name = "ACC_DISTANCE_CONFIG_1",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_SPEED_CONFIG_KPH",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_SPEED_CONFIG_MPH",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_STATE",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 36,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_DISTANCE_CONFIG_2",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 40,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_DIGITAL",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_512[] = {
    {
      .name = "COUNTER",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "NEW_SIGNAL_1",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 32,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_514[] = {
    {
      .name = "SPEED_LEFT",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 12,
      .size = 12,
      .is_signed = false,
      .factor = 0.071028,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_RIGHT",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 28,
      .size = 12,
      .is_signed = false,
      .factor = 0.071028,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_532[] = {
    {
      .name = "ENERGY_RELATED",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 8,
      .size = 9,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NOISY_SLOWLY_DECREASING",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 24,
      .size = 9,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_544[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "TORQUE_DRIVER",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 8,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = -1024.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TORQUE_MOTOR_RAW",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 24,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = -2048.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_STATE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 20,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TORQUE_MOTOR",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 40,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = -1024.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_HAS_CONTROL_2",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_559[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACCEL_22F",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 0,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_571[] = {
    {
      .name = "COUNTER",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "ACC_CANCEL",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_FOLLOW_DEC",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 1,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_SPEED_INC",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_SPEED_DEC",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_RESUME",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_FOLLOW_INC",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_608[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "IN_REVERSE",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_HAS_CONTROL_1",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUMAN_HAS_CONTROL",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PARKSENSE_DISABLED",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_625[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "SPEED",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_PERHAPS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 40,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_639[] = {
    {
      .name = "INCREASING",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_653[] = {
    {
      .name = "BRAKE_PRESSED",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSURE",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_655[] = {
    {
      .name = "CHARGING",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_658[] = {
    {
      .name = "COUNTER",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "LKAS_STEERING_TORQUE",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 8,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = -1024.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_HIGH_TORQUE",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_660[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
    {
      .name = "BRAKE_PERHAPS_294",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_669[] = {
    {
      .name = "COUNTER",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::CHRYSLER_CHECKSUM,
    },
};
const Signal sigs_671[] = {
    {
      .name = "AUTO_PARK_CMD",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 8,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = -1024.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_STATUS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 3,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_MODE",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 21,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_678[] = {
    {
      .name = "LKAS_ICON_COLOR",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAR_MODEL",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_LANE_LINES",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 16,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_ALERTS",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_701[] = {
    {
      .name = "unknown_1",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_705[] = {
    {
      .name = "AUTO_PARK_TOGGLE_2",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_TOGGLE_1",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_UNKNOWN",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 32,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_719[] = {
    {
      .name = "AUTO_PARK_UNKNOWN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_720[] = {
    {
      .name = "BLIND_SPOT_LEFT",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BLIND_SPOT_RIGHT",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_729[] = {
    {
      .name = "LKAS_STATUS_OK",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 32,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_736[] = {
    {
      .name = "COUNTER",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_746[] = {
    {
      .name = "COUNTER",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 28,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PRNDL",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR_CHECKSUM",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_764[] = {
    {
      .name = "ACCEL_2FC",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 8,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_784[] = {
    {
      .name = "INCREASING_UNKNOWN",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_PERPENDICULAR_2",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 61,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_792[] = {
    {
      .name = "TURN_SIGNALS",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_PUSHED_IN",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_FLASH",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_816[] = {
    {
      .name = "TRACTION_OFF",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TOGGLE_PARKSENSE",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_820[] = {
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_TRUNK",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TURN_LIGHT_RIGHT",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 30,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TURN_LIGHT_LEFT",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_DISPLAY",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_825[] = {
    {
      .name = "BEEP_339",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_826[] = {
    {
      .name = "AUTO_PARK_HAS_CONTROL_3",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 1,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUMAN_HAS_CONTROL",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_GEAR_1",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_GEAR_2",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_PARK_GEAR_3",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_832[] = {
    {
      .name = "SPEED_DIGITAL",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_848[] = {
    {
      .name = "INCREASING_LSB",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 0,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_MSB",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 8,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_878[] = {
    {
      .name = "ACCEL_OR_RPM_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_OR_RPM_2",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_908[] = {
    {
      .name = "INCREASING_MSB",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 40,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_LSB",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 56,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_938[] = {
    {
      .name = "INCREASING_UNKNOWN_1",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_UNKNOWN_2",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_940[] = {
    {
      .name = "INCREASING_1",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_2",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_941[] = {
    {
      .name = "INCREASING_1",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 32,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_2",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "ACCEL_RELATED_a8",
    .address = 0xA8,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_168),
    .sigs = sigs_168,
  },
  {
    .name = "ACCEL_RELATED_101",
    .address = 0x101,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_257),
    .sigs = sigs_257,
  },
  {
    .name = "STEERING",
    .address = 0x102,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_258),
    .sigs = sigs_258,
  },
  {
    .name = "ACCEL_PEDAL_MSG",
    .address = 0x108,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_264),
    .sigs = sigs_264,
  },
  {
    .name = "ACC_10c",
    .address = 0x10C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_268),
    .sigs = sigs_268,
  },
  {
    .name = "ACCEL_RELATED_10e",
    .address = 0x10E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_270),
    .sigs = sigs_270,
  },
  {
    .name = "BRAKE_1",
    .address = 0x11C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_284),
    .sigs = sigs_284,
  },
  {
    .name = "ACCEL_RELATED_120",
    .address = 0x120,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_288),
    .sigs = sigs_288,
  },
  {
    .name = "ENERGY_RELATED_123",
    .address = 0x123,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_291),
    .sigs = sigs_291,
  },
  {
    .name = "ENERGY_RELATED_126",
    .address = 0x126,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_294),
    .sigs = sigs_294,
  },
  {
    .name = "ACCEL_GAS_134",
    .address = 0x134,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_308),
    .sigs = sigs_308,
  },
  {
    .name = "BRAKE_2",
    .address = 0x140,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_320),
    .sigs = sigs_320,
  },
  {
    .name = "SPEED_2",
    .address = 0x144,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_324),
    .sigs = sigs_324,
  },
  {
    .name = "BRAKE_3",
    .address = 0x14B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_331),
    .sigs = sigs_331,
  },
  {
    .name = "STEERING_2",
    .address = 0x14C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_332),
    .sigs = sigs_332,
  },
  {
    .name = "WHEEL_SPEEDS",
    .address = 0x158,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_344),
    .sigs = sigs_344,
  },
  {
    .name = "NEW_MSG_180",
    .address = 0x180,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_384),
    .sigs = sigs_384,
  },
  {
    .name = "SEATBELT_STATUS",
    .address = 0x1D0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_464),
    .sigs = sigs_464,
  },
  {
    .name = "ACC_2",
    .address = 0x1F4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_500),
    .sigs = sigs_500,
  },
  {
    .name = "DASHBOARD",
    .address = 0x1F5,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_501),
    .sigs = sigs_501,
  },
  {
    .name = "NEW_MSG_200",
    .address = 0x200,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_512),
    .sigs = sigs_512,
  },
  {
    .name = "SPEED_1",
    .address = 0x202,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_514),
    .sigs = sigs_514,
  },
  {
    .name = "ENERGY_RELATED_214",
    .address = 0x214,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_532),
    .sigs = sigs_532,
  },
  {
    .name = "EPS_STATUS",
    .address = 0x220,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_544),
    .sigs = sigs_544,
  },
  {
    .name = "ACCEL_GAS_22F",
    .address = 0x22F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_559),
    .sigs = sigs_559,
  },
  {
    .name = "WHEEL_BUTTONS",
    .address = 0x23B,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_571),
    .sigs = sigs_571,
  },
  {
    .name = "PARKSENSE_SIGNAL",
    .address = 0x260,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_608),
    .sigs = sigs_608,
  },
  {
    .name = "ACC_1",
    .address = 0x271,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_625),
    .sigs = sigs_625,
  },
  {
    .name = "NEW_MSG_27f",
    .address = 0x27F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_639),
    .sigs = sigs_639,
  },
  {
    .name = "BRAKE_MODULE",
    .address = 0x28D,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_653),
    .sigs = sigs_653,
  },
  {
    .name = "CHARGING_MAYBE_28F",
    .address = 0x28F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_655),
    .sigs = sigs_655,
  },
  {
    .name = "LKAS_COMMAND",
    .address = 0x292,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_658),
    .sigs = sigs_658,
  },
  {
    .name = "BRAKE_RELATED_294",
    .address = 0x294,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_660),
    .sigs = sigs_660,
  },
  {
    .name = "NEW_MSG_29d",
    .address = 0x29D,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_669),
    .sigs = sigs_669,
  },
  {
    .name = "AUTO_PARK_REQUEST",
    .address = 0x29F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_671),
    .sigs = sigs_671,
  },
  {
    .name = "LKAS_HUD",
    .address = 0x2A6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_678),
    .sigs = sigs_678,
  },
  {
    .name = "NEW_MSG_2bd",
    .address = 0x2BD,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_701),
    .sigs = sigs_701,
  },
  {
    .name = "AUTO_PARK_BUTTON",
    .address = 0x2C1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_705),
    .sigs = sigs_705,
  },
  {
    .name = "AUTO_PARK_SIGNALS_1",
    .address = 0x2CF,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_719),
    .sigs = sigs_719,
  },
  {
    .name = "BLIND_SPOT_WARNINGS",
    .address = 0x2D0,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_720),
    .sigs = sigs_720,
  },
  {
    .name = "LKAS_HEARTBIT",
    .address = 0x2D9,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_729),
    .sigs = sigs_729,
  },
  {
    .name = "TRIP",
    .address = 0x2E0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_736),
    .sigs = sigs_736,
  },
  {
    .name = "GEAR",
    .address = 0x2EA,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_746),
    .sigs = sigs_746,
  },
  {
    .name = "ACCEL_RELATED_2FC",
    .address = 0x2FC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_764),
    .sigs = sigs_764,
  },
  {
    .name = "AUTO_PARK_LESS_INTERESTING",
    .address = 0x310,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_784),
    .sigs = sigs_784,
  },
  {
    .name = "STEERING_LEVERS",
    .address = 0x318,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_792),
    .sigs = sigs_792,
  },
  {
    .name = "TRACTION_BUTTON",
    .address = 0x330,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_816),
    .sigs = sigs_816,
  },
  {
    .name = "DOORS",
    .address = 0x334,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_820),
    .sigs = sigs_820,
  },
  {
    .name = "AUDIBLE_BEEP_339",
    .address = 0x339,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_825),
    .sigs = sigs_825,
  },
  {
    .name = "AUTO_PARK_SIGNALS_3",
    .address = 0x33A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_826),
    .sigs = sigs_826,
  },
  {
    .name = "UNKNOWN_340",
    .address = 0x340,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_832),
    .sigs = sigs_832,
  },
  {
    .name = "UNKNOWN_350",
    .address = 0x350,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_848),
    .sigs = sigs_848,
  },
  {
    .name = "ACCEL_RELATED_36E",
    .address = 0x36E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_878),
    .sigs = sigs_878,
  },
  {
    .name = "NEW_MSG_38c",
    .address = 0x38C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_908),
    .sigs = sigs_908,
  },
  {
    .name = "NEW_MSG_3aa",
    .address = 0x3AA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_938),
    .sigs = sigs_938,
  },
  {
    .name = "NEW_MSG_3ac",
    .address = 0x3AC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_940),
    .sigs = sigs_940,
  },
  {
    .name = "NEW_MSG_3ad",
    .address = 0x3AD,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_941),
    .sigs = sigs_941,
  },
};

const Val vals[] = {
    {
      .name = "CRUISE_STATE",
      .address = 0x1F5,
      .def_val = "0 OFF 1 CC_ON 2 CC_ENGAGED 3 ACC_ON 4 ACC_ENGAGED",
      .sigs = sigs_501,
    },
    {
      .name = "PRNDL",
      .address = 0x2EA,
      .def_val = "5 L 4 D 3 N 2 R 1 P",
      .sigs = sigs_746,
    },
    {
      .name = "TURN_SIGNALS",
      .address = 0x318,
      .def_val = "2 RIGHT 1 LEFT",
      .sigs = sigs_792,
    },
};

}

const DBC chrysler_pacifica_2017_hybrid = {
  .name = "chrysler_pacifica_2017_hybrid",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(chrysler_pacifica_2017_hybrid)