#include "common_dbc.h"

namespace {

const Signal sigs_189[] = {
    {
      .name = "RegenPaddle",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_190[] = {
    {
      .name = "BrakePedalPos",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasPedalAndAcc",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_201[] = {
    {
      .name = "Standstill",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EngineRPM",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 16,
      .size = 16,
      .is_signed = false,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CruiseMainOn",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EngineTPS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 0.392156863,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pressed",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_209[] = {
    {
      .name = "BrakePedalPosition1",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 8,
      .size = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 6,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakePedalPosition2",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 24,
      .size = 14,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 22,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakeNormalized1",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakeNormalized2",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_241[] = {
    {
      .name = "BrakePedalPosition",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_298[] = {
    {
      .name = "RearLeftDoor",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FrontLeftDoor",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FrontRightDoor",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LeftSeatBelt",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RearRightDoor",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RightSeatBelt",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 53,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_309[] = {
    {
      .name = "PRNDL",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESPButton",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_320[] = {
    {
      .name = "HighBeamsTemporary",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HighBeamsActive",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Intellibeam",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TurnSignals",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 18,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_352[] = {
    {
      .name = "Ignition",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 24,
      .size = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_381[] = {
    {
      .name = "TractionControlOn",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MSG17D_AccPower",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_384[] = {
    {
      .name = "LKASteeringCmd",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 8,
      .size = 11,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKASteeringCmdActive",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RollingCounter",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 4,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKASteeringCmdChecksum",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 24,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_388[] = {
    {
      .name = "LKATotalTorqueDelivered",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 8,
      .size = 11,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKATorqueDeliveredStatus",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 3,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKATorqueDelivered",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 24,
      .size = 11,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HandsOffSWDetectionMode",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 19,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HandsOffSWlDetectionStatus",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKADriverAppldTrq",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 56,
      .size = 11,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_417[] = {
    {
      .name = "AcceleratorPedal",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_451[] = {
    {
      .name = "GasPedalAndAcc2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_452[] = {
    {
      .name = "CruiseState",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AcceleratorPedal2",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_481[] = {
    {
      .name = "DistanceButton",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAButton",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DriveModeButton",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCButtons",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 44,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_485[] = {
    {
      .name = "SteeringWheelAngle",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 16,
      .size = 16,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SteeringWheelRate",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 32,
      .size = 12,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_489[] = {
    {
      .name = "LateralAcceleration",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 10,
      .size = 10,
      .is_signed = true,
      .factor = 0.161,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakePedalPressed",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "YawRate",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = true,
      .factor = 0.625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "YawRate2",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 56,
      .size = 12,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_497[] = {
    {
      .name = "Ignition",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_501[] = {
    {
      .name = "PRNDL2",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ManualMode",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TransmissionState",
      .start_bit = 48,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_512[] = {
    {
      .name = "GAS_COMMAND",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.125677,
      .offset = -75.909,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_COMMAND2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.251976,
      .offset = -76.601,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "ENABLE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_513[] = {
    {
      .name = "INTERCEPTOR_GAS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.125677,
      .offset = -75.909,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INTERCEPTOR_GAS2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.251976,
      .offset = -76.601,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "STATE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_560[] = {
    {
      .name = "EPBClosed",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_711[] = {
    {
      .name = "HVBatteryCurrent",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 16,
      .size = 13,
      .is_signed = true,
      .factor = 0.15,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HVBatteryVoltage",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 36,
      .size = 12,
      .is_signed = false,
      .factor = 0.125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_715[] = {
    {
      .name = "GasRegenCmdActive",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RollingCounter",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 6,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenAlwaysOne2",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenFullStopActive",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenAlwaysOne",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenCmd",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 27,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenAlwaysOne3",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenCmdActiveInv",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasRegenChecksum",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 56,
      .size = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_789[] = {
    {
      .name = "FrictionBrakeCmd",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FrictionBrakeMode",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FrictionBrakeChecksum",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RollingCounter",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 32,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_800[] = {
    {
      .name = "BrakingForce",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 12,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakeCmdActive",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RollingCounter",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 4,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 40,
      .size = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_810[] = {
    {
      .name = "GPSLatitude",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 24,
      .size = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GPSLongitude",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 56,
      .size = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -2147483648.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_840[] = {
    {
      .name = "FLWheelSpd",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.0311,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRWheelSpd",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.0311,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_842[] = {
    {
      .name = "RLWheelSpd",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.0311,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RRWheelSpd",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.0311,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_880[] = {
    {
      .name = "ACCAlwaysOne",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCResumeButton",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 1,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCSpeedSetpoint",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 24,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCGapLevel",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 20,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCCmdActive",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCAlwaysOne2",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCWAlert",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 40,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCLeadCar",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1001[] = {
    {
      .name = "VehicleSpeed",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1033[] = {
    {
      .name = "ASCMKeepAliveAllZero",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 48,
      .size = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1217[] = {
    {
      .name = "EngineCoolantTemp",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1249[] = {
    {
      .name = "VINPart2",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 56,
      .size = 64,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1300[] = {
    {
      .name = "VINPart1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 56,
      .size = 64,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "EBCMRegenPaddle",
    .address = 0xBD,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_189),
    .sigs = sigs_189,
  },
  {
    .name = "ECMAcceleratorPos",
    .address = 0xBE,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_190),
    .sigs = sigs_190,
  },
  {
    .name = "ECMEngineStatus",
    .address = 0xC9,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_201),
    .sigs = sigs_201,
  },
  {
    .name = "EBCMBrakePedalSensors",
    .address = 0xD1,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_209),
    .sigs = sigs_209,
  },
  {
    .name = "EBCMBrakePedalPosition",
    .address = 0xF1,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_241),
    .sigs = sigs_241,
  },
  {
    .name = "BCMDoorBeltStatus",
    .address = 0x12A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_298),
    .sigs = sigs_298,
  },
  {
    .name = "ECMPRDNL",
    .address = 0x135,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_309),
    .sigs = sigs_309,
  },
  {
    .name = "BCMTurnSignals",
    .address = 0x140,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_320),
    .sigs = sigs_320,
  },
  {
    .name = "VehicleIgnition",
    .address = 0x160,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_352),
    .sigs = sigs_352,
  },
  {
    .name = "ESPStatus",
    .address = 0x17D,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_381),
    .sigs = sigs_381,
  },
  {
    .name = "ASCMLKASteeringCmd",
    .address = 0x180,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_384),
    .sigs = sigs_384,
  },
  {
    .name = "PSCMStatus",
    .address = 0x184,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_388),
    .sigs = sigs_388,
  },
  {
    .name = "AcceleratorPedal",
    .address = 0x1A1,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_417),
    .sigs = sigs_417,
  },
  {
    .name = "GasAndAcc",
    .address = 0x1C3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_451),
    .sigs = sigs_451,
  },
  {
    .name = "AcceleratorPedal2",
    .address = 0x1C4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_452),
    .sigs = sigs_452,
  },
  {
    .name = "ASCMSteeringButton",
    .address = 0x1E1,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_481),
    .sigs = sigs_481,
  },
  {
    .name = "PSCMSteeringAngle",
    .address = 0x1E5,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_485),
    .sigs = sigs_485,
  },
  {
    .name = "EBCMVehicleDynamic",
    .address = 0x1E9,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_489),
    .sigs = sigs_489,
  },
  {
    .name = "VehicleIgnitionAlt",
    .address = 0x1F1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_497),
    .sigs = sigs_497,
  },
  {
    .name = "ECMPRDNL2",
    .address = 0x1F5,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_501),
    .sigs = sigs_501,
  },
  {
    .name = "GAS_COMMAND",
    .address = 0x200,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_512),
    .sigs = sigs_512,
  },
  {
    .name = "GAS_SENSOR",
    .address = 0x201,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_513),
    .sigs = sigs_513,
  },
  {
    .name = "EPBStatus",
    .address = 0x230,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_560),
    .sigs = sigs_560,
  },
  {
    .name = "BECMBatteryVoltageCurrent",
    .address = 0x2C7,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_711),
    .sigs = sigs_711,
  },
  {
    .name = "ASCMGasRegenCmd",
    .address = 0x2CB,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_715),
    .sigs = sigs_715,
  },
  {
    .name = "EBCMFrictionBrakeCmd",
    .address = 0x315,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_789),
    .sigs = sigs_789,
  },
  {
    .name = "AEBCmd",
    .address = 0x320,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_800),
    .sigs = sigs_800,
  },
  {
    .name = "TCICOnStarGPSPosition",
    .address = 0x32A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_810),
    .sigs = sigs_810,
  },
  {
    .name = "EBCMWheelSpdFront",
    .address = 0x348,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_840),
    .sigs = sigs_840,
  },
  {
    .name = "EBCMWheelSpdRear",
    .address = 0x34A,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_842),
    .sigs = sigs_842,
  },
  {
    .name = "ASCMActiveCruiseControlStatus",
    .address = 0x370,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_880),
    .sigs = sigs_880,
  },
  {
    .name = "ECMVehicleSpeed",
    .address = 0x3E9,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1001),
    .sigs = sigs_1001,
  },
  {
    .name = "ASCMKeepAlive",
    .address = 0x409,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_1033),
    .sigs = sigs_1033,
  },
  {
    .name = "ECMEngineCoolantTemp",
    .address = 0x4C1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1217),
    .sigs = sigs_1217,
  },
  {
    .name = "VIN_Part2",
    .address = 0x4E1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1249),
    .sigs = sigs_1249,
  },
  {
    .name = "VIN_Part1",
    .address = 0x514,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1300),
    .sigs = sigs_1300,
  },
};

const Val vals[] = {
    {
      .name = "ESPButton",
      .address = 0x135,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_309,
    },
    {
      .name = "PRNDL",
      .address = 0x135,
      .def_val = "3 R 2 D 1 N 0 P",
      .sigs = sigs_309,
    },
    {
      .name = "HighBeamsActive",
      .address = 0x140,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_320,
    },
    {
      .name = "HighBeamsTemporary",
      .address = 0x140,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_320,
    },
    {
      .name = "Intellibeam",
      .address = 0x140,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_320,
    },
    {
      .name = "LKASteeringCmdActive",
      .address = 0x180,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_384,
    },
    {
      .name = "HandsOffSWDetectionMode",
      .address = 0x184,
      .def_val = "2 FAILED 1 ENABLED 0 DISABLED",
      .sigs = sigs_388,
    },
    {
      .name = "HandsOffSWlDetectionStatus",
      .address = 0x184,
      .def_val = "1 HANDS_ON 0 HANDS_OFF",
      .sigs = sigs_388,
    },
    {
      .name = "LKATorqueDeliveredStatus",
      .address = 0x184,
      .def_val = "3 FAILED 2 TEMP._LIMITED 1 ACTIVE 0 INACTIVE",
      .sigs = sigs_388,
    },
    {
      .name = "CruiseState",
      .address = 0x1C4,
      .def_val = "4 STANDSTILL 3 FAULTED 1 ACTIVE 0 OFF",
      .sigs = sigs_452,
    },
    {
      .name = "ACCButtons",
      .address = 0x1E1,
      .def_val = "6 CANCEL 5 MAIN 3 SET 2 RESUME 1 NONE",
      .sigs = sigs_481,
    },
    {
      .name = "DistanceButton",
      .address = 0x1E1,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_481,
    },
    {
      .name = "DriveModeButton",
      .address = 0x1E1,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_481,
    },
    {
      .name = "LKAButton",
      .address = 0x1E1,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_481,
    },
    {
      .name = "BrakePedalPressed",
      .address = 0x1E9,
      .def_val = "1 PRESSED 0 DEPRESSED",
      .sigs = sigs_489,
    },
    {
      .name = "ManualMode",
      .address = 0x1F5,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_501,
    },
    {
      .name = "PRNDL2",
      .address = 0x1F5,
      .def_val = "6 L 4 D 3 N 2 R 1 P 0 SHIFTING",
      .sigs = sigs_501,
    },
    {
      .name = "TransmissionState",
      .address = 0x1F5,
      .def_val = "11 SHIFTING 10 REVERSE 9 FORWARD 8 DISENGAGED",
      .sigs = sigs_501,
    },
    {
      .name = "STATE",
      .address = 0x201,
      .def_val = "5 FAULT_TIMEOUT 4 FAULT_STARTUP 3 FAULT_SCE 2 FAULT_SEND 1 FAULT_BAD_CHECKSUM 0 NO_FAULT",
      .sigs = sigs_513,
    },
    {
      .name = "GasRegenCmdActive",
      .address = 0x2CB,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_715,
    },
    {
      .name = "GasRegenCmdActiveInv",
      .address = 0x2CB,
      .def_val = "1 INACTIVE 0 ACTIVE",
      .sigs = sigs_715,
    },
    {
      .name = "ACCCmdActive",
      .address = 0x370,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_880,
    },
    {
      .name = "ACCGapLevel",
      .address = 0x370,
      .def_val = "3 FAR 2 MED 1 NEAR 0 INACTIVE",
      .sigs = sigs_880,
    },
    {
      .name = "ACCLeadCar",
      .address = 0x370,
      .def_val = "1 PRESENT 0 NOT_PRESENT",
      .sigs = sigs_880,
    },
    {
      .name = "ACCResumeButton",
      .address = 0x370,
      .def_val = "1 PRESSED 0 DEPRESSED",
      .sigs = sigs_880,
    },
};

}

const DBC gm_global_a_powertrain_generated = {
  .name = "gm_global_a_powertrain_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(gm_global_a_powertrain_generated)