#include "common_dbc.h"

namespace {

const Signal sigs_145[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 14,
      .size = 10,
      .is_signed = false,
      .factor = 0.02,
      .offset = -512.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_148[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 14,
      .size = 10,
      .is_signed = false,
      .factor = 0.02,
      .offset = -512.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_ACCEL",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 32,
      .size = 9,
      .is_signed = true,
      .factor = -0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_228[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 36,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 16,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_REQUEST",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_2",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_304[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ENGINE_TORQUE_ESTIMATE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_TORQUE_REQUEST",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAR_GAS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_316[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CAR_GAS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_342[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 40,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 44,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_ANGLE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_344[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "XMISSION_SPEED",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "XMISSION_SPEED2",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 40,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ODOMETER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_380[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "PEDAL_GAS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_SWITCH",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_17C",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 33,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_STATUS",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PRESSED",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH2_17C",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 54,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH3_17C",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 48,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSED",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 53,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_399[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 52,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE_SENSOR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_CONTROL_ACTIVE",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_STATUS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_CONFIG_INDEX",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 40,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_401[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GEAR_SHIFTER",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 0,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 40,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_420[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "USER_BRAKE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -1.609375,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COMPUTER_BRAKING",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_DISABLED",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ENABLED",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ACTIVE",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_RELATED",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_422[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LIGHTS_SETTING",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_BUTTONS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 5,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SETTING",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 42,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAIN_ON",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DRIVERS_DOOR_OPEN",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 63,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_427[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 16,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 20,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "MOTOR_TORQUE",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 8,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CONFIG_VALID",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OUTPUT_DISABLED",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_432[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 52,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CONTROLLED_STANDSTILL",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_ERROR_2",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_ERROR_1",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEELS_MOVING",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_464[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 9,
      .size = 15,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 26,
      .size = 15,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 43,
      .size = 15,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 60,
      .size = 15,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_487[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 28,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "BRAKE_PRESSURE1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 14,
      .size = 10,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -103.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSURE2",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 16,
      .size = 10,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -103.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_490[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 0.0015,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_ACCEL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = 0.0015,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_506[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "COMPUTER_BRAKE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 14,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PUMP_REQUEST",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 9,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COMPUTER_BRAKE_REQUEST",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CANCEL_CMD",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_FAULT_CMD",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_3",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_OVERRIDE",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 21,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_REQ_2",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 24,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_REQ_1",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_1",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_STATES",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 32,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_LIGHTS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_STATUS",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 40,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCW",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 42,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_4",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHIME",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 45,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_5",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_512[] = {
    {
      .name = "GAS_COMMAND",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.253984064,
      .offset = -83.3,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_COMMAND2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.126992032,
      .offset = -83.3,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "ENABLE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_513[] = {
    {
      .name = "INTERCEPTOR_GAS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INTERCEPTOR_GAS2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "STATE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_597[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X55",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X55_2",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_660[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WIPERS_SPEED",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 3,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_773[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 52,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SEATBELT_DRIVER_LAMP",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_UNLATCHED",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_LATCHED",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_UNLATCHED",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_LATCHED",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_OFF",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_ON",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_777[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DOORS_UNLOCKED",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOORS_LOCKED",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_780[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "PCM_SPEED",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCM_GAS",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SPEED",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENABLE_MINI_CAR",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RADAR_OBSTRUCTED",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_PROBLEM",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_OFF_2",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_OFF",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_PROBLEM",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC_MODE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CONTROL_LABEL",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_5",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_4",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_3",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_LEAD",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 44,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_DISTANCE",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 46,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X01",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHIME",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 49,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_DISTANCE_3",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "IMPERIAL_UNIT",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X01_2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ICONS",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 62,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_804[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "HUD_SPEED_KPH",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_SPEED_MPH",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRIP_FUEL_CONSUMED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SPEED_PCM",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH2",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH3",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_829[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 36,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_ME_X41",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 0,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 0,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAM_TEMP_HIGH",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_REQUIRED",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_RIGHT",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SOLID_LANES",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_OFF",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_PROBLEM",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASHED_LANES",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BEEP",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_PROBLEM",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 22,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CLEAN_WINDSHIELD",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 26,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_OFF",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_ON",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X48",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_862[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ZEROS_BOH",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 54,
      .size = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH_2",
      .start_bit = 48,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGHBEAMS_ON",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HIGHBEAMS_ACTIVE",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 53,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_884[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DASHBOARD_ALERT",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_FLASH",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HEADLIGHTS",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_HOLD",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WIPER_SWITCH",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 52,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HEADLIGHTS_ON",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_891[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WIPERS",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAMS",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOW_BEAMS",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PARK_LIGHTS",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_892[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CRUISE_SPEED_OFFSET",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1029[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRUNK_OPEN",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "KINEMATICS",
    .address = 0x91,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_145),
    .sigs = sigs_145,
  },
  {
    .name = "KINEMATICS_ALT",
    .address = 0x94,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_148),
    .sigs = sigs_148,
  },
  {
    .name = "STEERING_CONTROL",
    .address = 0xE4,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_228),
    .sigs = sigs_228,
  },
  {
    .name = "GAS_PEDAL_2",
    .address = 0x130,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_304),
    .sigs = sigs_304,
  },
  {
    .name = "GAS_PEDAL",
    .address = 0x13C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_316),
    .sigs = sigs_316,
  },
  {
    .name = "STEERING_SENSORS",
    .address = 0x156,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_342),
    .sigs = sigs_342,
  },
  {
    .name = "ENGINE_DATA",
    .address = 0x158,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_344),
    .sigs = sigs_344,
  },
  {
    .name = "POWERTRAIN_DATA",
    .address = 0x17C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_380),
    .sigs = sigs_380,
  },
  {
    .name = "STEER_STATUS",
    .address = 0x18F,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_399),
    .sigs = sigs_399,
  },
  {
    .name = "GEARBOX",
    .address = 0x191,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_401),
    .sigs = sigs_401,
  },
  {
    .name = "VSA_STATUS",
    .address = 0x1A4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_420),
    .sigs = sigs_420,
  },
  {
    .name = "SCM_BUTTONS",
    .address = 0x1A6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_422),
    .sigs = sigs_422,
  },
  {
    .name = "STEER_MOTOR_TORQUE",
    .address = 0x1AB,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_427),
    .sigs = sigs_427,
  },
  {
    .name = "STANDSTILL",
    .address = 0x1B0,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_432),
    .sigs = sigs_432,
  },
  {
    .name = "WHEEL_SPEEDS",
    .address = 0x1D0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_464),
    .sigs = sigs_464,
  },
  {
    .name = "BRAKE_PRESSURE",
    .address = 0x1E7,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_487),
    .sigs = sigs_487,
  },
  {
    .name = "VEHICLE_DYNAMICS",
    .address = 0x1EA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_490),
    .sigs = sigs_490,
  },
  {
    .name = "BRAKE_COMMAND",
    .address = 0x1FA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_506),
    .sigs = sigs_506,
  },
  {
    .name = "GAS_COMMAND",
    .address = 0x200,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_512),
    .sigs = sigs_512,
  },
  {
    .name = "GAS_SENSOR",
    .address = 0x201,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_513),
    .sigs = sigs_513,
  },
  {
    .name = "ROUGH_WHEEL_SPEED",
    .address = 0x255,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_597),
    .sigs = sigs_597,
  },
  {
    .name = "SCM_FEEDBACK",
    .address = 0x294,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_660),
    .sigs = sigs_660,
  },
  {
    .name = "SEATBELT_STATUS",
    .address = 0x305,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_773),
    .sigs = sigs_773,
  },
  {
    .name = "LOCK_STATUS",
    .address = 0x309,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_777),
    .sigs = sigs_777,
  },
  {
    .name = "ACC_HUD",
    .address = 0x30C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_780),
    .sigs = sigs_780,
  },
  {
    .name = "CRUISE",
    .address = 0x324,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_804),
    .sigs = sigs_804,
  },
  {
    .name = "LKAS_HUD",
    .address = 0x33D,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_829),
    .sigs = sigs_829,
  },
  {
    .name = "HIGHBEAM_CONTROL",
    .address = 0x35E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_862),
    .sigs = sigs_862,
  },
  {
    .name = "STALK_STATUS",
    .address = 0x374,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_884),
    .sigs = sigs_884,
  },
  {
    .name = "STALK_STATUS_2",
    .address = 0x37B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_891),
    .sigs = sigs_891,
  },
  {
    .name = "CRUISE_PARAMS",
    .address = 0x37C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_892),
    .sigs = sigs_892,
  },
  {
    .name = "DOORS_STATUS",
    .address = 0x405,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1029),
    .sigs = sigs_1029,
  },
};

const Val vals[] = {
    {
      .name = "STEER_STATUS",
      .address = 0x18F,
      .def_val = "6 TMP_FAULT 5 FAULT_1 4 NO_TORQUE_ALERT_2 3 LOW_SPEED_LOCKOUT 2 NO_TORQUE_ALERT_1 0 NORMAL",
      .sigs = sigs_399,
    },
    {
      .name = "GEAR",
      .address = 0x191,
      .def_val = "7 L 10 S 4 D 3 N 2 R 1 P",
      .sigs = sigs_401,
    },
    {
      .name = "GEAR_SHIFTER",
      .address = 0x191,
      .def_val = "32 L 16 S 8 D 4 N 2 R 1 P",
      .sigs = sigs_401,
    },
    {
      .name = "CRUISE_BUTTONS",
      .address = 0x1A6,
      .def_val = "7 TBD 6 TBD 5 TBD 4 ACCEL_RES 3 DECEL_SET 2 CANCEL 1 MAIN 0 NONE",
      .sigs = sigs_422,
    },
    {
      .name = "CRUISE_SETTING",
      .address = 0x1A6,
      .def_val = "3 DISTANCE_ADJ 2 TBD 1 LKAS_BUTTON 0 NONE",
      .sigs = sigs_422,
    },
    {
      .name = "LIGHTS_SETTING",
      .address = 0x1A6,
      .def_val = "3 HIGH_BEAM 2 LOW_BEAM 1 POSITION 0 NO_LIGHTS",
      .sigs = sigs_422,
    },
    {
      .name = "AEB_STATUS",
      .address = 0x1FA,
      .def_val = "3 AEB_PREPARE 2 AEB_READY 1 AEB_BRAKING 0 NO_AEB",
      .sigs = sigs_506,
    },
    {
      .name = "CHIME",
      .address = 0x1FA,
      .def_val = "4 DOUBLE_CHIME 3 SINGLE_CHIME 2 CONTINUOUS_CHIME 1 REPEATING_CHIME 0 NO_CHIME",
      .sigs = sigs_506,
    },
    {
      .name = "FCW",
      .address = 0x1FA,
      .def_val = "3 FCW 2 FCW 1 FCW 0 NO_FCW",
      .sigs = sigs_506,
    },
    {
      .name = "STATE",
      .address = 0x201,
      .def_val = "5 FAULT_TIMEOUT 4 FAULT_STARTUP 3 FAULT_SCE 2 FAULT_SEND 1 FAULT_BAD_CHECKSUM 0 NO_FAULT",
      .sigs = sigs_513,
    },
    {
      .name = "CRUISE_SPEED",
      .address = 0x30C,
      .def_val = "255 NO_SPEED 252 STOPPED",
      .sigs = sigs_780,
    },
    {
      .name = "HUD_LEAD",
      .address = 0x30C,
      .def_val = "3 ACC_OFF 2 SOLID_CAR 1 DASHED_CAR 0 NO_CAR",
      .sigs = sigs_780,
    },
    {
      .name = "BEEP",
      .address = 0x33D,
      .def_val = "3 SINGLE_BEEP 2 TRIPLE_BEEP 1 REPEATED_BEEP 0 NO_BEEP",
      .sigs = sigs_829,
    },
    {
      .name = "DASHBOARD_ALERT",
      .address = 0x374,
      .def_val = "0 NONE 51 ACC_PROBLEM 55 CMBS_PROBLEM 75 KEY_NOT_DETECTED 79 FASTEN_SEATBELT 111 LKAS_PROBLEM 131 BRAKE_SYSTEM_PROBLEM 132 BRAKE_HOLD_PROBLEM 139 TBD 161 DOOR_OPEN",
      .sigs = sigs_884,
    },
    {
      .name = "WIPERS",
      .address = 0x37B,
      .def_val = "4 HIGH 2 LOW 0 OFF",
      .sigs = sigs_891,
    },
};

}

const DBC honda_fit_ex_2018_can_generated = {
  .name = "honda_fit_ex_2018_can_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(honda_fit_ex_2018_can_generated)