#include "common_dbc.h"

namespace {

const Signal sigs_2[] = {
    {
      .name = "COUNTER",
      .start_bit = 32,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE",
      .start_bit = 0,
      .msb  = 15,
      .lsb = 0,
      .size = 16,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .start_bit = 16,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X07",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_348[] = {
    {
      .name = "GAS_PEDAL_RAW",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 32,
      .size = 11,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 54,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_361[] = {
    {
      .name = "COUNTER",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DESIRED_ANGLE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 22,
      .size = 18,
      .is_signed = false,
      .factor = -0.01,
      .offset = 1310,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_0x80_2",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAX_TORQUE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_0x80",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKA_ACTIVE",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_389[] = {
    {
      .name = "COUNTER",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_DRIVER",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 12,
      .size = 12,
      .is_signed = false,
      .factor = -0.01,
      .offset = 20.47,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 38,
      .size = 18,
      .is_signed = false,
      .factor = -0.01,
      .offset = 1310,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_ACTIVE",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_LKAS",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_438[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X03",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 32,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_ON",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_ACTIVATED",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_STATUS",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_523[] = {
    {
      .name = "COUNTER",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unsure1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 14,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PROPILOT_BUTTON",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CANCEL_BUTTON",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FOLLOW_DISTANCE_BUTTON",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_BUTTON",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RES_BUTTON",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NO_BUTTON_PRESSED",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unsure3",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 18,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PRESSED_INVERTED",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "USER_BRAKE_PRESSED",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "USER_BRAKE_PRESSED_INVERTED",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PEDAL",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 38,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PEDAL_INVERTED",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 44,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unsure2",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 40,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_645[] = {
    {
      .name = "WHEEL_SPEED_RR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_665[] = {
    {
      .name = "ESP_DISABLED",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_666[] = {
    {
      .name = "WHEEL_SPEED_FR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_689[] = {
    {
      .name = "unknown02",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FOLLOW_DISTANCE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 2,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown05",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 4,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_SET_ICON",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 6,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown08",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 18,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LARGE_WARNING_FLASHING",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_ERROR_FLASHING1",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_ERROR_FLASHING2",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_LANE_YELLOW_FLASH",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_LANE_YELLOW_FLASH",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_CAR",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_CAR_ERROR",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_RADAR_ERROR",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_RADAR_ERROR_FLASHING",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_LANE_GREEN",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_LANE_GREEN",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown26",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 26,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_ERROR_FLASHING3",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown28",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_ERROR_FLASHING",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown31",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 30,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_SPEED",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SMALL_STEERING_WHEEL_ICON",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 40,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown43",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SAFETY_SHIELD_ACTIVE",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUDIBLE_TONE",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 45,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown55",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown59",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LARGE_STEERING_WHEEL_ICON",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_LANE_GREEN_FLASH",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_LANE_GREEN_FLASH",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 63,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_768[] = {
    {
      .name = "STEERING_TORQUE",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 0,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_PRESSED",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = -1.0,
      .offset = 1,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_783[] = {
    {
      .name = "CRUISE_ENABLED",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1055[] = {
    {
      .name = "GEAR_SHIFTER",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 3,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPORTS_MODE",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1107[] = {
    {
      .name = "HEADLIGHTS",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1108[] = {
    {
      .name = "USER_BRAKE_PRESSED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_RR",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_RL",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_FL",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_FR",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_LIGHT",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOOT_OPEN",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1227[] = {
    {
      .name = "LKAS_ENABLED",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1228[] = {
    {
      .name = "NA_HIGH_ACCEL_TEMP",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown07",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 1,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_NA_HIGH_CABIN_TEMP",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown10",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 9,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_MALFUNCTION",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 11,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_MALFUNCTION",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_RADAR_MALFUNCTION",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_NA_CLEAN_REAR_CAMERA",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown15",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NA_POOR_ROAD_CONDITIONS",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CURRENTLY_UNAVAILABLE",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SAFETY_SHIELD_OFF",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown19",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_COLLISION_NA_FRONT_RADAR_OBSTRUCTION",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown23",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 21,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PEDAL_MISSAPPLICATION_SYSTEM_ACTIVATED",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_IMPACT_NA_RADAR_OBSTRUCTION",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown31",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 26,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown32",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WARNING_DO_NOT_ENTER",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_IMPACT_SYSTEM_OFF",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_IMPACT_MALFUNCTION",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_COLLISION_MALFUNCTION",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SIDE_RADAR_MALFUNCTION2",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_MALFUNCTION2",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_RADAR_MALFUNCTION2",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PROPILOT_NA_MSGS",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 40,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOTTOM_MSG",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 43,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown46",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HANDS_ON_WHEEL_WARNING",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown50",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WARNING_STEP_ON_BRAKE_NOW",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PROPILOT_NA_FRONT_CAMERA_OBSTRUCTED",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PROPILOT_NA_HIGH_CABIN_TEMP",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 53,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WARNING_PROPILOT_MALFUNCTION",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown55",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "unknown61",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 56,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_UNAVAILABLE_HIGH_CABIN_TEMP",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_NA_FRONT_CAMERA_IMPARED",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 63,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1273[] = {
    {
      .name = "SPEED_MPH",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_LATCHED",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "STEER_ANGLE_SENSOR",
    .address = 0x2,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_2),
    .sigs = sigs_2,
  },
  {
    .name = "GAS_PEDAL",
    .address = 0x15C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_348),
    .sigs = sigs_348,
  },
  {
    .name = "LKAS",
    .address = 0x169,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_361),
    .sigs = sigs_361,
  },
  {
    .name = "STEER_TORQUE_SENSOR",
    .address = 0x185,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_389),
    .sigs = sigs_389,
  },
  {
    .name = "PRO_PILOT",
    .address = 0x1B6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_438),
    .sigs = sigs_438,
  },
  {
    .name = "CRUISE_THROTTLE",
    .address = 0x20B,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_523),
    .sigs = sigs_523,
  },
  {
    .name = "WHEEL_SPEEDS_REAR",
    .address = 0x285,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_645),
    .sigs = sigs_645,
  },
  {
    .name = "ESP",
    .address = 0x299,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_665),
    .sigs = sigs_665,
  },
  {
    .name = "WHEEL_SPEEDS_FRONT",
    .address = 0x29A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_666),
    .sigs = sigs_666,
  },
  {
    .name = "PROPILOT_HUD",
    .address = 0x2B1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_689),
    .sigs = sigs_689,
  },
  {
    .name = "STEER_TORQUE_SENSOR2",
    .address = 0x300,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_768),
    .sigs = sigs_768,
  },
  {
    .name = "CRUISE_STATE",
    .address = 0x30F,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_783),
    .sigs = sigs_783,
  },
  {
    .name = "GEARBOX",
    .address = 0x41F,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_1055),
    .sigs = sigs_1055,
  },
  {
    .name = "LIGHTS",
    .address = 0x453,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1107),
    .sigs = sigs_1107,
  },
  {
    .name = "DOORS_LIGHTS",
    .address = 0x454,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1108),
    .sigs = sigs_1108,
  },
  {
    .name = "LKAS_SETTINGS",
    .address = 0x4CB,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1227),
    .sigs = sigs_1227,
  },
  {
    .name = "PROPILOT_HUD_INFO_MSG",
    .address = 0x4CC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1228),
    .sigs = sigs_1228,
  },
  {
    .name = "HUD",
    .address = 0x4F9,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_1273),
    .sigs = sigs_1273,
  },
};

const Val vals[] = {
    {
      .name = "AUDIBLE_TONE",
      .address = 0x2B1,
      .def_val = "0 NO_TONE 1 CONT 2 FAST_BEEP_CONT 3 TRIPLE_FAST_BEEP_CONT 4 SLOW_BEEP_CONT 5 QUAD_SLOW_BEEP_CONT 6 SINGLE_BEEP_ONCE 7 DOUBLE_BEEP_ONCE",
      .sigs = sigs_689,
    },
    {
      .name = "FOLLOW_DISTANCE",
      .address = 0x2B1,
      .def_val = "0 NO_FOLLOW_DISTANCE 1 FOLLOW_DISTANCE_1 2 FOLLOW_DISTANCE_2 3 FOLLOW_DISANCE_3",
      .sigs = sigs_689,
    },
    {
      .name = "LARGE_STEERING_WHEEL_ICON",
      .address = 0x2B1,
      .def_val = "0 NO_STEERINGWHEEL 1 GRAY_STEERINGWHEEL 2 GREEN_STEERINGWHEEL 3 GREEN_STEERINGWHEEL_FLASHING",
      .sigs = sigs_689,
    },
    {
      .name = "SMALL_STEERING_WHEEL_ICON",
      .address = 0x2B1,
      .def_val = "0 NO_ICON 1 GRAY_ICON 2 GRAY_ICON_FLASHING 3 GREEN_ICON 4 GREEN_ICON_FLASHING 5 RED_ICON 6 RED_ICON_FLASHING 7 YELLOW_ICON",
      .sigs = sigs_689,
    },
    {
      .name = "GEAR_SHIFTER",
      .address = 0x41F,
      .def_val = "6 L 4 D 3 N 2 R 1 P",
      .sigs = sigs_1055,
    },
    {
      .name = "BOTTOM_MSG",
      .address = 0x4CC,
      .def_val = "0 OK_STEER_ASSIST_SETTINGS 1 NO_MSG 2 PRESS_SET_TO_SET_SPEED 3 PRESS_RES_SET_TO_CHANGE_SPEED 4 PRESS_RES_TO_RESTART 5 NO_MSG 6 CRUISE_NOT_AVAIL 7 NO_MSG",
      .sigs = sigs_1228,
    },
    {
      .name = "PROPILOT_NA_MSGS",
      .address = 0x4CC,
      .def_val = "0 NO_MSG 1 NA_FRONT_CAMERA_IMPARED 2 STEERING_ASSIST_ON_STANDBY 3 NA_PARKING_ASSIST_ENABLED 4 STEER_ASSIST_CURRENTLY_NA 5 NA_BAD_WEATHER 6 NA_PARK_BRAKE_ON 7 NA_SEATBELT_NOT_FASTENED",
      .sigs = sigs_1228,
    },
};

}

const DBC nissan_x_trail_2017 = {
  .name = "nissan_x_trail_2017",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(nissan_x_trail_2017)