#include "common_dbc.h"

namespace {

const Signal sigs_2[] = {
    {
      .name = "Steering_Angle",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 25,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_208[] = {
    {
      .name = "Steering_Angle",
      .start_bit = 0,
      .msb  = 15,
      .lsb = 0,
      .size = 16,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Lateral",
      .start_bit = 16,
      .msb  = 31,
      .lsb = 16,
      .size = 16,
      .is_signed = true,
      .factor = -0.0035,
      .offset = 1,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Longitudinal",
      .start_bit = 48,
      .msb  = 63,
      .lsb = 48,
      .size = 16,
      .is_signed = true,
      .factor = -0.00035,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_209[] = {
    {
      .name = "Speed",
      .start_bit = 0,
      .msb  = 15,
      .lsb = 0,
      .size = 16,
      .is_signed = false,
      .factor = 0.05625,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pedal",
      .start_bit = 16,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_210[] = {
    {
      .name = "Brake_Light",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Related",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Right_Brake",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Left_Brake",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_211[] = {
    {
      .name = "Brake_Light",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Speed_Counter",
      .start_bit = 32,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Cruise_On",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pedal_On",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_212[] = {
    {
      .name = "FL",
      .start_bit = 0,
      .msb  = 15,
      .lsb = 0,
      .size = 16,
      .is_signed = false,
      .factor = 0.0592,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FR",
      .start_bit = 16,
      .msb  = 31,
      .lsb = 16,
      .size = 16,
      .is_signed = false,
      .factor = 0.0592,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RL",
      .start_bit = 32,
      .msb  = 47,
      .lsb = 32,
      .size = 16,
      .is_signed = false,
      .factor = 0.0592,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RR",
      .start_bit = 48,
      .msb  = 63,
      .lsb = 48,
      .size = 16,
      .is_signed = false,
      .factor = 0.0592,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_320[] = {
    {
      .name = "Throttle_Pedal",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 0.392157,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 13,
      .lsb = 12,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Not_Full_Throttle",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Engine_RPM",
      .start_bit = 16,
      .msb  = 29,
      .lsb = 16,
      .size = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Off_Throttle",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 30,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Cruise",
      .start_bit = 32,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Combo",
      .start_bit = 40,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Body",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Off_Throttle_2",
      .start_bit = 56,
      .msb  = 56,
      .lsb = 56,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal4",
      .start_bit = 57,
      .msb  = 63,
      .lsb = 57,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_321[] = {
    {
      .name = "Engine_Torque",
      .start_bit = 0,
      .msb  = 14,
      .lsb = 0,
      .size = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Engine_Stop",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Wheel_Torque",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Engine_RPM",
      .start_bit = 32,
      .msb  = 43,
      .lsb = 32,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_324[] = {
    {
      .name = "OnOffButton",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_BUTTON",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RES_BUTTON",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Button",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 49,
      .msb  = 49,
      .lsb = 49,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pedal_On",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_328[] = {
    {
      .name = "Manual_Gear",
      .start_bit = 4,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Transmission_Engine",
      .start_bit = 16,
      .msb  = 30,
      .lsb = 16,
      .size = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Gear",
      .start_bit = 48,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Gear_2",
      .start_bit = 52,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Paddle_Shift",
      .start_bit = 60,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_336[] = {
    {
      .name = "Brake_Pressure_Right",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pressure_Left",
      .start_bit = 8,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_338[] = {
    {
      .name = "Counter",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Light",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Runlights",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Headlights",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 59,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Highbeam",
      .start_bit = 60,
      .msb  = 60,
      .lsb = 60,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Wiper",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_352[] = {
    {
      .name = "Brake_Pressure",
      .start_bit = 0,
      .msb  = 15,
      .lsb = 0,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Light",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_On",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 48,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_353[] = {
    {
      .name = "Cruise_Throttle",
      .start_bit = 0,
      .msb  = 11,
      .lsb = 0,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Car_Follow",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 17,
      .msb  = 19,
      .lsb = 17,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_On",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Distance_Swap",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Standstill",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 22,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Close_Distance",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 0.0196,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal4",
      .start_bit = 32,
      .msb  = 40,
      .lsb = 32,
      .size = 9,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Standstill_2",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal5",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 44,
      .msb  = 46,
      .lsb = 44,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal6",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Button",
      .start_bit = 48,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal7",
      .start_bit = 51,
      .msb  = 55,
      .lsb = 51,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_354[] = {
    {
      .name = "Brake",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 9,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RPM",
      .start_bit = 16,
      .msb  = 31,
      .lsb = 16,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 32,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 48,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_356[] = {
    {
      .name = "Counter",
      .start_bit = 0,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Command",
      .start_bit = 8,
      .msb  = 20,
      .lsb = 8,
      .size = 13,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Active",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_358[] = {
    {
      .name = "Not_Ready_Startup",
      .start_bit = 0,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Seatbelt_Disengage",
      .start_bit = 12,
      .msb  = 13,
      .lsb = 12,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Disengage_Alert",
      .start_bit = 14,
      .msb  = 15,
      .lsb = 14,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEELS_MOVING_2015",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Driver_Input",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Distance",
      .start_bit = 21,
      .msb  = 23,
      .lsb = 21,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Set_Speed",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On_2",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 37,
      .msb  = 39,
      .lsb = 37,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steep_Hill_Disengage",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Car_Follow",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Far_Distance",
      .start_bit = 48,
      .msb  = 51,
      .lsb = 48,
      .size = 4,
      .is_signed = false,
      .factor = 5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_359[] = {
    {
      .name = "All_depart_2015",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Right_Line_2017",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Left_Line_2017",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig1All_Depart",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig2All_Depart",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Inactive_2017",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Active",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig1Right_Depart",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig1Right_Depart_Front",
      .start_bit = 49,
      .msb  = 49,
      .lsb = 49,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig2Right_Depart",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 50,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Left_Depart_Front",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Sig3All_Depart",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_604[] = {
    {
      .name = "Counter",
      .start_bit = 0,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "State",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "R_ADJACENT",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "L_ADJACENT",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "R_APPROACHING",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "L_APPROACHING",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "R_RCTA",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "L_RCTA",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_642[] = {
    {
      .name = "Counter",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_FL",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_864[] = {
    {
      .name = "Oil_Temp",
      .start_bit = 16,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Coolant_Temp",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Saved_Speed",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_880[] = {
    {
      .name = "Steering_Voltage_Flat",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Torque_Sensor",
      .start_bit = 29,
      .msb  = 39,
      .lsb = 29,
      .size = 11,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 40,
      .msb  = 43,
      .lsb = 40,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_881[] = {
    {
      .name = "Steering_Motor_Flat",
      .start_bit = 0,
      .msb  = 9,
      .lsb = 0,
      .size = 10,
      .is_signed = false,
      .factor = 32,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Torque_Output",
      .start_bit = 16,
      .msb  = 26,
      .lsb = 16,
      .size = 11,
      .is_signed = true,
      .factor = -32.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Error_1",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Torque_Sensor",
      .start_bit = 29,
      .msb  = 39,
      .lsb = 29,
      .size = 11,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steering_Angle",
      .start_bit = 40,
      .msb  = 55,
      .lsb = 40,
      .size = 16,
      .is_signed = true,
      .factor = -0.033,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_884[] = {
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 26,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_Hatch",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_977[] = {
    {
      .name = "UNITS",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1745[] = {
    {
      .name = "Units",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "Steering",
    .address = 0x2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_2),
    .sigs = sigs_2,
  },
  {
    .name = "G_Sensor",
    .address = 0xD0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_208),
    .sigs = sigs_208,
  },
  {
    .name = "Brake_Pedal",
    .address = 0xD1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_209),
    .sigs = sigs_209,
  },
  {
    .name = "Brake_2",
    .address = 0xD2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_210),
    .sigs = sigs_210,
  },
  {
    .name = "Brake_Type",
    .address = 0xD3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_211),
    .sigs = sigs_211,
  },
  {
    .name = "Wheel_Speeds",
    .address = 0xD4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_212),
    .sigs = sigs_212,
  },
  {
    .name = "Throttle",
    .address = 0x140,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_320),
    .sigs = sigs_320,
  },
  {
    .name = "Engine",
    .address = 0x141,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_321),
    .sigs = sigs_321,
  },
  {
    .name = "CruiseControl",
    .address = 0x144,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_324),
    .sigs = sigs_324,
  },
  {
    .name = "Transmission",
    .address = 0x148,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_328),
    .sigs = sigs_328,
  },
  {
    .name = "Brake_Pressure",
    .address = 0x150,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_336),
    .sigs = sigs_336,
  },
  {
    .name = "Stalk",
    .address = 0x152,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_338),
    .sigs = sigs_338,
  },
  {
    .name = "ES_Brake",
    .address = 0x160,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_352),
    .sigs = sigs_352,
  },
  {
    .name = "ES_Distance",
    .address = 0x161,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_353),
    .sigs = sigs_353,
  },
  {
    .name = "ES_RPM",
    .address = 0x162,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_354),
    .sigs = sigs_354,
  },
  {
    .name = "ES_LKAS",
    .address = 0x164,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_356),
    .sigs = sigs_356,
  },
  {
    .name = "ES_DashStatus",
    .address = 0x166,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_358),
    .sigs = sigs_358,
  },
  {
    .name = "ES_LDW",
    .address = 0x167,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_359),
    .sigs = sigs_359,
  },
  {
    .name = "BSD_RCTA",
    .address = 0x25C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_604),
    .sigs = sigs_604,
  },
  {
    .name = "Dashlights",
    .address = 0x282,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_642),
    .sigs = sigs_642,
  },
  {
    .name = "Engine_Temp",
    .address = 0x360,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_864),
    .sigs = sigs_864,
  },
  {
    .name = "Steering_Torque_2",
    .address = 0x370,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_880),
    .sigs = sigs_880,
  },
  {
    .name = "Steering_Torque",
    .address = 0x371,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_881),
    .sigs = sigs_881,
  },
  {
    .name = "BodyInfo",
    .address = 0x374,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_884),
    .sigs = sigs_884,
  },
  {
    .name = "Dash_State2",
    .address = 0x3D1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_977),
    .sigs = sigs_977,
  },
  {
    .name = "Dash_State",
    .address = 0x6D1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1745),
    .sigs = sigs_1745,
  },
};

const Val vals[] = {
    {
      .name = "Gear",
      .address = 0x148,
      .def_val = "0 N 1 D 2 D 3 D 4 D 5 D 6 D 14 R 15 P",
      .sigs = sigs_328,
    },
};

}

const DBC subaru_outback_2015_generated = {
  .name = "subaru_outback_2015_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(subaru_outback_2015_generated)