#include "common_dbc.h"

namespace {

const Signal sigs_2[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 32,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Steering_Angle",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .start_bit = 25,
      .msb  = 27,
      .lsb = 25,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_64[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Engine_RPM",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 28,
      .msb  = 31,
      .lsb = 28,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Pedal",
      .start_bit = 32,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Cruise",
      .start_bit = 40,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Throttle_Combo",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 56,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Off_Accel",
      .start_bit = 60,
      .msb  = 63,
      .lsb = 60,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_72[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Gear",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RPM",
      .start_bit = 40,
      .msb  = 55,
      .lsb = 40,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_73[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CVT_Gear",
      .start_bit = 24,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_280[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "State",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 63,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_281[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Error_1",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Torque_Sensor",
      .start_bit = 16,
      .msb  = 26,
      .lsb = 16,
      .size = 11,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Error_2",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Warning",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steering_Angle",
      .start_bit = 32,
      .msb  = 47,
      .lsb = 32,
      .size = 16,
      .is_signed = true,
      .factor = -0.0217,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steer_Torque_Output",
      .start_bit = 48,
      .msb  = 58,
      .lsb = 48,
      .size = 11,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_290[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_1",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Output",
      .start_bit = 16,
      .msb  = 28,
      .lsb = 16,
      .size = 13,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Request",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_312[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_1",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_2",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_313[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Speed",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 0.05625,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 28,
      .msb  = 33,
      .lsb = 28,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Lights",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pedal",
      .start_bit = 36,
      .msb  = 47,
      .lsb = 36,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal4",
      .start_bit = 48,
      .msb  = 63,
      .lsb = 48,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_314[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FR",
      .start_bit = 12,
      .msb  = 24,
      .lsb = 12,
      .size = 13,
      .is_signed = false,
      .factor = 0.057,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RR",
      .start_bit = 25,
      .msb  = 37,
      .lsb = 25,
      .size = 13,
      .is_signed = false,
      .factor = 0.057,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RL",
      .start_bit = 38,
      .msb  = 50,
      .lsb = 38,
      .size = 13,
      .is_signed = false,
      .factor = 0.057,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FL",
      .start_bit = 51,
      .msb  = 63,
      .lsb = 51,
      .size = 13,
      .is_signed = false,
      .factor = 0.057,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_315[] = {
    {
      .name = "Lateral",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Longitudinal",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_316[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 57,
      .lsb = 12,
      .size = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ES_Brake",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 59,
      .msb  = 61,
      .lsb = 59,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 63,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_326[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 41,
      .lsb = 12,
      .size = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Main",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Set",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Resume",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 45,
      .msb  = 63,
      .lsb = 45,
      .size = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_372[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STOP_START_STATE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 38,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_544[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Pressure",
      .start_bit = 16,
      .msb  = 31,
      .lsb = 16,
      .size = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 32,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Brake_Lights",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Brake_Fault",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Brake_Active",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 40,
      .msb  = 63,
      .lsb = 40,
      .size = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_545[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 14,
      .lsb = 12,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Throttle",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 28,
      .msb  = 31,
      .lsb = 28,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Car_Follow",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 33,
      .msb  = 35,
      .lsb = 33,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Brake_Active",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Distance_Swap",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_EPB",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal4",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Close_Distance",
      .start_bit = 40,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal5",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Cancel",
      .start_bit = 56,
      .msb  = 56,
      .lsb = 56,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Set",
      .start_bit = 57,
      .msb  = 57,
      .lsb = 57,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Resume",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal6",
      .start_bit = 59,
      .msb  = 63,
      .lsb = 59,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_546[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 14,
      .lsb = 12,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_RPM",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Lights",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 30,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Hold",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 32,
      .msb  = 63,
      .lsb = 32,
      .size = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_552[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "R_ADJACENT",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "L_ADJACENT",
      .start_bit = 49,
      .msb  = 49,
      .lsb = 49,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "R_APPROACHING",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "L_APPROACHING",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 59,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_576[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 12,
      .msb  = 39,
      .lsb = 12,
      .size = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 42,
      .msb  = 63,
      .lsb = 42,
      .size = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_577[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Active",
      .start_bit = 57,
      .msb  = 60,
      .lsb = 57,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_722[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AC_ON",
      .start_bit = 24,
      .msb  = 25,
      .lsb = 24,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AC_Mode",
      .start_bit = 37,
      .msb  = 39,
      .lsb = 37,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_801[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCB_Off",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_Off",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 14,
      .msb  = 15,
      .lsb = 14,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_State_Msg",
      .start_bit = 16,
      .msb  = 19,
      .lsb = 16,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_State_Msg",
      .start_bit = 20,
      .msb  = 22,
      .lsb = 20,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Soft_Disable",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Status_Msg",
      .start_bit = 25,
      .msb  = 26,
      .lsb = 25,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Distance",
      .start_bit = 28,
      .msb  = 30,
      .lsb = 28,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal4",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Conventional_Cruise",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal5",
      .start_bit = 33,
      .msb  = 34,
      .lsb = 33,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Disengaged",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Activated",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal6",
      .start_bit = 37,
      .msb  = 39,
      .lsb = 37,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Set_Speed",
      .start_bit = 40,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_Fault",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_On",
      .start_bit = 49,
      .msb  = 49,
      .lsb = 49,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Display_Own_Car",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 50,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Brake_Lights",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Car_Follow",
      .start_bit = 52,
      .msb  = 52,
      .lsb = 52,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal7",
      .start_bit = 53,
      .msb  = 55,
      .lsb = 53,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Far_Distance",
      .start_bit = 56,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Cruise_State",
      .start_bit = 60,
      .msb  = 63,
      .lsb = 60,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_802[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Alert_Msg",
      .start_bit = 12,
      .msb  = 14,
      .lsb = 12,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal1",
      .start_bit = 15,
      .msb  = 16,
      .lsb = 15,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_ACTIVE",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 17,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Dash_State",
      .start_bit = 18,
      .msb  = 19,
      .lsb = 18,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal2",
      .start_bit = 20,
      .msb  = 22,
      .lsb = 20,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Backward_Speed_Limit_Menu",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Left_Line_Enable",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Left_Line_Light_Blink",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Right_Line_Enable",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 26,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Right_Line_Light_Blink",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Left_Line_Visible",
      .start_bit = 28,
      .msb  = 29,
      .lsb = 28,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Right_Line_Visible",
      .start_bit = 30,
      .msb  = 31,
      .lsb = 30,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_Alert",
      .start_bit = 32,
      .msb  = 36,
      .lsb = 32,
      .size = 5,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Signal3",
      .start_bit = 37,
      .msb  = 63,
      .lsb = 37,
      .size = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_912[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UNITS",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ICY_ROAD",
      .start_bit = 32,
      .msb  = 33,
      .lsb = 32,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_FL",
      .start_bit = 48,
      .msb  = 48,
      .lsb = 48,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 50,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .start_bit = 51,
      .msb  = 51,
      .lsb = 51,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STOP_START",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_940[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_TRUNK",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASH_BTN_LIGHTS",
      .start_bit = 56,
      .msb  = 56,
      .lsb = 56,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOWBEAM",
      .start_bit = 57,
      .msb  = 57,
      .lsb = 57,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGHBEAM",
      .start_bit = 58,
      .msb  = 58,
      .lsb = 58,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FOG_LIGHTS",
      .start_bit = 60,
      .msb  = 60,
      .lsb = 60,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WIPERS",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1677[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 0,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::SUBARU_CHECKSUM,
    },
    {
      .name = "Counter",
      .start_bit = 8,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Units",
      .start_bit = 29,
      .msb  = 31,
      .lsb = 29,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "Steering",
    .address = 0x2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_2),
    .sigs = sigs_2,
  },
  {
    .name = "Throttle",
    .address = 0x40,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_64),
    .sigs = sigs_64,
  },
  {
    .name = "Transmission",
    .address = 0x48,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_72),
    .sigs = sigs_72,
  },
  {
    .name = "CVT",
    .address = 0x49,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_73),
    .sigs = sigs_73,
  },
  {
    .name = "STOP_START",
    .address = 0x118,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_280),
    .sigs = sigs_280,
  },
  {
    .name = "Steering_Torque",
    .address = 0x119,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_281),
    .sigs = sigs_281,
  },
  {
    .name = "ES_LKAS",
    .address = 0x122,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_290),
    .sigs = sigs_290,
  },
  {
    .name = "Brake_Pressure_L_R",
    .address = 0x138,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_312),
    .sigs = sigs_312,
  },
  {
    .name = "Brake_Pedal",
    .address = 0x139,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_313),
    .sigs = sigs_313,
  },
  {
    .name = "Wheel_Speeds",
    .address = 0x13A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_314),
    .sigs = sigs_314,
  },
  {
    .name = "G_Sensor",
    .address = 0x13B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_315),
    .sigs = sigs_315,
  },
  {
    .name = "Brake_Status",
    .address = 0x13C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_316),
    .sigs = sigs_316,
  },
  {
    .name = "Cruise_Buttons",
    .address = 0x146,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_326),
    .sigs = sigs_326,
  },
  {
    .name = "Engine_Stop_Start",
    .address = 0x174,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_372),
    .sigs = sigs_372,
  },
  {
    .name = "ES_Brake",
    .address = 0x220,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_544),
    .sigs = sigs_544,
  },
  {
    .name = "ES_Distance",
    .address = 0x221,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_545),
    .sigs = sigs_545,
  },
  {
    .name = "ES_Status",
    .address = 0x222,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_546),
    .sigs = sigs_546,
  },
  {
    .name = "BSD_RCTA",
    .address = 0x228,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_552),
    .sigs = sigs_552,
  },
  {
    .name = "CruiseControl",
    .address = 0x240,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_576),
    .sigs = sigs_576,
  },
  {
    .name = "Cruise_Status",
    .address = 0x241,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_577),
    .sigs = sigs_577,
  },
  {
    .name = "AC_State",
    .address = 0x2D2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_722),
    .sigs = sigs_722,
  },
  {
    .name = "ES_DashStatus",
    .address = 0x321,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_801),
    .sigs = sigs_801,
  },
  {
    .name = "ES_LKAS_State",
    .address = 0x322,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_802),
    .sigs = sigs_802,
  },
  {
    .name = "Dashlights",
    .address = 0x390,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_912),
    .sigs = sigs_912,
  },
  {
    .name = "BodyInfo",
    .address = 0x3AC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_940),
    .sigs = sigs_940,
  },
  {
    .name = "Dash_State",
    .address = 0x68D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1677),
    .sigs = sigs_1677,
  },
};

const Val vals[] = {
    {
      .name = "Gear",
      .address = 0x48,
      .def_val = "2 N 3 R 4 P 121 D 137 1 145 2 153 3 161 4 169 5 177 6",
      .sigs = sigs_72,
    },
};

}

const DBC subaru_global_2017_generated = {
  .name = "subaru_global_2017_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(subaru_global_2017_generated)