#include "common_dbc.h"

namespace {

const Signal sigs_262[] = {
    {
      .name = "DI_torqueDriver",
      .start_bit = 0,
      .msb  = 12,
      .lsb = 0,
      .size = 13,
      .is_signed = true,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque1Counter",
      .start_bit = 13,
      .msb  = 15,
      .lsb = 13,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torqueMotor",
      .start_bit = 16,
      .msb  = 28,
      .lsb = 16,
      .size = 13,
      .is_signed = true,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_soptState",
      .start_bit = 29,
      .msb  = 31,
      .lsb = 29,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_motorRPM",
      .start_bit = 32,
      .msb  = 47,
      .lsb = 32,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_pedalPos",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 0.4,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque1Checksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_278[] = {
    {
      .name = "DI_torqueEstimate",
      .start_bit = 0,
      .msb  = 11,
      .lsb = 0,
      .size = 12,
      .is_signed = true,
      .factor = 0.5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_gear",
      .start_bit = 12,
      .msb  = 14,
      .lsb = 12,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_brakePedal",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_vehicleSpeed",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 0.05,
      .offset = -25.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_gearRequest",
      .start_bit = 28,
      .msb  = 30,
      .lsb = 28,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torqueInterfaceFailure",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque2Counter",
      .start_bit = 32,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_brakePedalState",
      .start_bit = 36,
      .msb  = 37,
      .lsb = 36,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_epbParkRequest",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_epbInterfaceReady",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque2Checksum",
      .start_bit = 40,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_504[] = {
    {
      .name = "driverBrakeStatus",
      .start_bit = 2,
      .msb  = 3,
      .lsb = 2,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_568[] = {
    {
      .name = "SpdCtrlLvr_Stat",
      .start_bit = 0,
      .msb  = 5,
      .lsb = 0,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VSL_Enbl_Rq",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SpdCtrlLvrStat_Inv",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTR_Dist_Rq",
      .start_bit = 8,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TurnIndLvr_Stat",
      .start_bit = 16,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HiBmLvr_Stat",
      .start_bit = 18,
      .msb  = 19,
      .lsb = 18,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprWashSw_Psd",
      .start_bit = 20,
      .msb  = 21,
      .lsb = 20,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprWash_R_Sw_Posn_V2",
      .start_bit = 22,
      .msb  = 23,
      .lsb = 22,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Lvr_Stat",
      .start_bit = 24,
      .msb  = 26,
      .lsb = 24,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Cond_Flt",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Cond_Psd",
      .start_bit = 28,
      .msb  = 29,
      .lsb = 28,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HrnSw_Psd",
      .start_bit = 30,
      .msb  = 31,
      .lsb = 30,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw00_Psd",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw01_Psd",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw02_Psd",
      .start_bit = 34,
      .msb  = 34,
      .lsb = 34,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw03_Psd",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 35,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw04_Psd",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw05_Psd",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw06_Psd",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw07_Psd",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw08_Psd",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw09_Psd",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw10_Psd",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw11_Psd",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw12_Psd",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw13_Psd",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw14_Psd",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw15_Psd",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprSw6Posn",
      .start_bit = 48,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MC_STW_ACTN_RQ",
      .start_bit = 52,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC_STW_ACTN_RQ",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_598[] = {
    {
      .name = "DI_systemState",
      .start_bit = 0,
      .msb  = 2,
      .lsb = 0,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_vehicleHoldState",
      .start_bit = 3,
      .msb  = 5,
      .lsb = 3,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_proximity",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_driveReady",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_regenLight",
      .start_bit = 8,
      .msb  = 8,
      .lsb = 8,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_state",
      .start_bit = 9,
      .msb  = 11,
      .lsb = 9,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_cruiseState",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_analogSpeed",
      .start_bit = 16,
      .msb  = 27,
      .lsb = 16,
      .size = 12,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_immobilizerState",
      .start_bit = 28,
      .msb  = 30,
      .lsb = 28,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_speedUnits",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_cruiseSet",
      .start_bit = 32,
      .msb  = 40,
      .lsb = 32,
      .size = 9,
      .is_signed = false,
      .factor = 0.5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_aebState",
      .start_bit = 41,
      .msb  = 43,
      .lsb = 41,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_stateCounter",
      .start_bit = 44,
      .msb  = 47,
      .lsb = 44,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_digitalSpeed",
      .start_bit = 48,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_stateChecksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_703[] = {
    {
      .name = "DAS_setSpeed",
      .start_bit = 0,
      .msb  = 11,
      .lsb = 0,
      .size = 12,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_accState",
      .start_bit = 12,
      .msb  = 15,
      .lsb = 12,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_aebEvent",
      .start_bit = 16,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_jerkMin",
      .start_bit = 18,
      .msb  = 26,
      .lsb = 18,
      .size = 9,
      .is_signed = false,
      .factor = 0.03,
      .offset = -15.232,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_jerkMax",
      .start_bit = 27,
      .msb  = 34,
      .lsb = 27,
      .size = 8,
      .is_signed = false,
      .factor = 0.059,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_accelMin",
      .start_bit = 35,
      .msb  = 43,
      .lsb = 35,
      .size = 9,
      .is_signed = false,
      .factor = 0.04,
      .offset = -15.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_accelMax",
      .start_bit = 44,
      .msb  = 52,
      .lsb = 44,
      .size = 9,
      .is_signed = false,
      .factor = 0.04,
      .offset = -15.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_controlCounter",
      .start_bit = 53,
      .msb  = 55,
      .lsb = 53,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_controlChecksum",
      .start_bit = 56,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "DI_torque1",
    .address = 0x106,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_262),
    .sigs = sigs_262,
  },
  {
    .name = "DI_torque2",
    .address = 0x116,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_278),
    .sigs = sigs_278,
  },
  {
    .name = "BrakeMessage",
    .address = 0x1F8,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_504),
    .sigs = sigs_504,
  },
  {
    .name = "STW_ACTN_RQ",
    .address = 0x238,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_568),
    .sigs = sigs_568,
  },
  {
    .name = "DI_state",
    .address = 0x256,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_598),
    .sigs = sigs_598,
  },
  {
    .name = "DAS_control",
    .address = 0x2BF,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_703),
    .sigs = sigs_703,
  },
};

const Val vals[] = {
    {
      .name = "DI_motorRPM",
      .address = 0x106,
      .def_val = "-32768 SNA",
      .sigs = sigs_262,
    },
    {
      .name = "DI_pedalPos",
      .address = 0x106,
      .def_val = "255 SNA",
      .sigs = sigs_262,
    },
    {
      .name = "DI_soptState",
      .address = 0x106,
      .def_val = "7 SOPT_TEST_SNA 4 SOPT_TEST_NOT_RUN 3 SOPT_TEST_PASSED 2 SOPT_TEST_FAILED 1 SOPT_TEST_IN_PROGRESS 0 SOPT_PRE_TEST",
      .sigs = sigs_262,
    },
    {
      .name = "DI_torqueDriver",
      .address = 0x106,
      .def_val = "-4096 SNA",
      .sigs = sigs_262,
    },
    {
      .name = "DI_torqueMotor",
      .address = 0x106,
      .def_val = "-4096 SNA",
      .sigs = sigs_262,
    },
    {
      .name = "DI_brakePedal",
      .address = 0x116,
      .def_val = "1 APPLIED 0 NOT_APPLIED",
      .sigs = sigs_278,
    },
    {
      .name = "DI_brakePedalState",
      .address = 0x116,
      .def_val = "3 SNA 2 INVALID 1 ON 0 OFF",
      .sigs = sigs_278,
    },
    {
      .name = "DI_epbInterfaceReady",
      .address = 0x116,
      .def_val = "1 EPB_INTERFACE_READY 0 EPB_INTERFACE_NOT_READY",
      .sigs = sigs_278,
    },
    {
      .name = "DI_epbParkRequest",
      .address = 0x116,
      .def_val = "1 PARK_REQUESTED 0 NO_REQUEST",
      .sigs = sigs_278,
    },
    {
      .name = "DI_gear",
      .address = 0x116,
      .def_val = "7 DI_GEAR_SNA 4 DI_GEAR_D 3 DI_GEAR_N 2 DI_GEAR_R 1 DI_GEAR_P 0 DI_GEAR_INVALID",
      .sigs = sigs_278,
    },
    {
      .name = "DI_gearRequest",
      .address = 0x116,
      .def_val = "7 DI_GEAR_SNA 4 DI_GEAR_D 3 DI_GEAR_N 2 DI_GEAR_R 1 DI_GEAR_P 0 DI_GEAR_INVALID",
      .sigs = sigs_278,
    },
    {
      .name = "DI_torqueEstimate",
      .address = 0x116,
      .def_val = "-2048 SNA",
      .sigs = sigs_278,
    },
    {
      .name = "DI_torqueInterfaceFailure",
      .address = 0x116,
      .def_val = "1 TORQUE_INTERFACE_FAILED 0 TORQUE_INTERFACE_NORMAL",
      .sigs = sigs_278,
    },
    {
      .name = "DI_vehicleSpeed",
      .address = 0x116,
      .def_val = "4095 SNA",
      .sigs = sigs_278,
    },
    {
      .name = "driverBrakeStatus",
      .address = 0x1F8,
      .def_val = "2 APPLIED 1 NOT_APPLIED",
      .sigs = sigs_504,
    },
    {
      .name = "DTR_Dist_Rq",
      .address = 0x238,
      .def_val = "255 SNA 200 ACC_DIST_7 166 ACC_DIST_6 133 ACC_DIST_5 100 ACC_DIST_4 66 ACC_DIST_3 33 ACC_DIST_2 0 ACC_DIST_1",
      .sigs = sigs_568,
    },
    {
      .name = "HiBmLvr_Stat",
      .address = 0x238,
      .def_val = "3 SNA 2 HIBM_FLSH_ON_PSD 1 HIBM_ON_PSD 0 IDLE",
      .sigs = sigs_568,
    },
    {
      .name = "HrnSw_Psd",
      .address = 0x238,
      .def_val = "3 SNA 2 NDEF2 1 PSD 0 NPSD",
      .sigs = sigs_568,
    },
    {
      .name = "SpdCtrlLvr_Stat",
      .address = 0x238,
      .def_val = "32 DN_1ST 16 UP_1ST 8 DN_2ND 4 UP_2ND 2 RWD 1 FWD 0 IDLE",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Cond_Psd",
      .address = 0x238,
      .def_val = "3 SNA 2 DOWN 1 UP 0 NPSD",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Lvr_Stat",
      .address = 0x238,
      .def_val = "4 STW_BACK 3 STW_FWD 2 STW_DOWN 1 STW_UP 0 NPSD",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Sw00_Psd",
      .address = 0x238,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Sw01_Psd",
      .address = 0x238,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Sw03_Psd",
      .address = 0x238,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_568,
    },
    {
      .name = "StW_Sw04_Psd",
      .address = 0x238,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_568,
    },
    {
      .name = "TurnIndLvr_Stat",
      .address = 0x238,
      .def_val = "3 SNA 2 RIGHT 1 LEFT 0 IDLE",
      .sigs = sigs_568,
    },
    {
      .name = "WprSw6Posn",
      .address = 0x238,
      .def_val = "7 SNA 6 STAGE2 5 STAGE1 4 INTERVAL4 3 INTERVAL3 2 INTERVAL2 1 INTERVAL1 0 OFF",
      .sigs = sigs_568,
    },
    {
      .name = "WprWashSw_Psd",
      .address = 0x238,
      .def_val = "3 SNA 2 WASH 1 TIPWIPE 0 NPSD",
      .sigs = sigs_568,
    },
    {
      .name = "WprWash_R_Sw_Posn_V2",
      .address = 0x238,
      .def_val = "3 SNA 2 WASH 1 INTERVAL 0 OFF",
      .sigs = sigs_568,
    },
    {
      .name = "DI_aebState",
      .address = 0x256,
      .def_val = "2 ENABLED 4 FAULT 7 SNA 1 STANDBY 3 STANDSTILL 0 UNAVAILABLE",
      .sigs = sigs_598,
    },
    {
      .name = "DI_analogSpeed",
      .address = 0x256,
      .def_val = "4095 SNA",
      .sigs = sigs_598,
    },
    {
      .name = "DI_cruiseState",
      .address = 0x256,
      .def_val = "2 ENABLED 5 FAULT 0 OFF 4 OVERRIDE 7 PRE_CANCEL 6 PRE_FAULT 1 STANDBY 3 STANDSTILL",
      .sigs = sigs_598,
    },
    {
      .name = "DI_digitalSpeed",
      .address = 0x256,
      .def_val = "255 SNA",
      .sigs = sigs_598,
    },
    {
      .name = "DI_immobilizerState",
      .address = 0x256,
      .def_val = "2 AUTHENTICATING 3 DISARMED 6 FAULT 4 IDLE 0 INIT_SNA 1 REQUEST 5 RESET",
      .sigs = sigs_598,
    },
    {
      .name = "DI_speedUnits",
      .address = 0x256,
      .def_val = "1 KPH 0 MPH",
      .sigs = sigs_598,
    },
    {
      .name = "DI_state",
      .address = 0x256,
      .def_val = "3 ABORT 4 ENABLE 2 FAULT 1 STANDBY 0 UNAVAILABLE",
      .sigs = sigs_598,
    },
    {
      .name = "DI_systemState",
      .address = 0x256,
      .def_val = "3 ABORT 4 ENABLE 2 FAULT 1 STANDBY 0 UNAVAILABLE",
      .sigs = sigs_598,
    },
    {
      .name = "DI_vehicleHoldState",
      .address = 0x256,
      .def_val = "2 BLEND_IN 4 BLEND_OUT 6 FAULT 7 INIT 5 PARK 1 STANDBY 3 STANDSTILL 0 UNAVAILABLE",
      .sigs = sigs_598,
    },
    {
      .name = "DAS_accState",
      .address = 0x2BF,
      .def_val = "15 FAULT_SNA 13 ACC_CANCEL_GENERIC_SILENT 11 APC_SELFPARK_START 10 APC_UNPARK_COMPLETE 9 APC_PAUSE 8 APC_ABORT 7 APC_COMPLETE 6 APC_FORWARD 5 APC_BACKWARD 4 ACC_ON 3 ACC_HOLD 0 ACC_CANCEL_GENERIC",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_accelMax",
      .address = 0x2BF,
      .def_val = "511 SNA",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_accelMin",
      .address = 0x2BF,
      .def_val = "511 SNA",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_aebEvent",
      .address = 0x2BF,
      .def_val = "3 AEB_SNA 2 AEB_FAULT 1 AEB_ACTIVE 0 AEB_NOT_ACTIVE",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_jerkMax",
      .address = 0x2BF,
      .def_val = "255 SNA",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_jerkMin",
      .address = 0x2BF,
      .def_val = "511 SNA",
      .sigs = sigs_703,
    },
    {
      .name = "DAS_setSpeed",
      .address = 0x2BF,
      .def_val = "4095 SNA",
      .sigs = sigs_703,
    },
};

}

const DBC tesla_powertrain = {
  .name = "tesla_powertrain",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(tesla_powertrain)