#include "common_dbc.h"

namespace {

const Signal sigs_35[] = {
    {
      .name = "ZORRO_STEER",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 16,
      .size = 24,
      .is_signed = true,
      .factor = 0.004901594652,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_36[] = {
    {
      .name = "YAW_RATE",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 8,
      .size = 10,
      .is_signed = false,
      .factor = 0.244,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_TORQUE",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 24,
      .size = 10,
      .is_signed = false,
      .factor = 1,
      .offset = -512.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_Y",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 40,
      .size = 10,
      .is_signed = false,
      .factor = 0.03589,
      .offset = -18.375,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_37[] = {
    {
      .name = "STEER_ANGLE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = true,
      .factor = 1.5,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_RATE",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 40,
      .size = 12,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_FRACTION",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_166[] = {
    {
      .name = "BRAKE_AMOUNT",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PEDAL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_170[] = {
    {
      .name = "WHEEL_SPEED_FR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 40,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 56,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_180[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "ENCODER",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 48,
      .size = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_295[] = {
    {
      .name = "COUNTER",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "CAR_MOVEMENT",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 44,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_353[] = {
    {
      .name = "FORWARD_SPEED",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 16,
      .size = 16,
      .is_signed = true,
      .factor = 0.00390625,
      .offset = -30.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_359[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "ANGLE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = true,
      .factor = 1.5,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X10",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DIRECTION_CMD",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 37,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X40",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_1",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_452[] = {
    {
      .name = "RPM",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 0.78125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_466[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "GAS_RELEASED",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_ACTIVE",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 5,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STANDSTILL_ON",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_NET",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = 0.001,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CANCEL_REQ",
      .start_bit = 49,
      .msb  = 49,
      .lsb = 49,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_STATE",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 52,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_467[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LOW_SPEED_LOCKOUT",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 13,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAIN_ON",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_SPEED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_512[] = {
    {
      .name = "GAS_COMMAND",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.159375,
      .offset = -75.555,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_COMMAND2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.159375,
      .offset = -151.111,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "ENABLE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 39,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_513[] = {
    {
      .name = "INTERCEPTOR_GAS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = false,
      .factor = 0.159375,
      .offset = -75.555,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INTERCEPTOR_GAS2",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = false,
      .factor = 0.159375,
      .offset = -151.111,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COUNTER_PEDAL",
      .start_bit = 35,
      .msb  = 35,
      .lsb = 32,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_COUNTER,
    },
    {
      .name = "STATE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 36,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM_PEDAL",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::PEDAL_CHECKSUM,
    },
};
const Signal sigs_550[] = {
    {
      .name = "BRAKE_PRESSURE",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 8,
      .size = 9,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_POSITION",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 24,
      .size = 9,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSED",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_552[] = {
    {
      .name = "ACCEL_X",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 8,
      .size = 15,
      .is_signed = true,
      .factor = 0.001,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_Z",
      .start_bit = 22,
      .msb  = 22,
      .lsb = 24,
      .size = 15,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_560[] = {
    {
      .name = "BRAKE_PRESSED",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 26,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_581[] = {
    {
      .name = "GAS_PEDAL",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_608[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "STEER_OVERRIDE",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_INITIALIZING",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_DRIVER",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 16,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 32,
      .size = 16,
      .is_signed = true,
      .factor = 0.0573,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_EPS",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 48,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_610[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "IPAS_STATE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 0,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TYPE",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKA_STATE",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 25,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_614[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "ANGLE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 8,
      .size = 12,
      .is_signed = true,
      .factor = 1.5,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X10",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DIRECTION_CMD",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 37,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X40",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_1",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_643[] = {
    {
      .name = "COUNTER",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "SET_ME_X00",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FORCE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 24,
      .size = 16,
      .is_signed = true,
      .factor = 2,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X002",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 42,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STATE",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 34,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_STATUS",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 37,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X003",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PRECOLLISION_ACTIVE",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_705[] = {
    {
      .name = "GAS_RELEASED",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PEDAL",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_740[] = {
    {
      .name = "COUNTER",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 1,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "STEER_REQUEST",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_CMD",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 16,
      .size = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKA_STATE",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_742[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LEAD_LONG_DIST",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 11,
      .size = 13,
      .is_signed = false,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_REL_SPEED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 28,
      .size = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_767[] = {
    {
      .name = "FD_BUTTON",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_835[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "ACCEL_CMD",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 8,
      .size = 16,
      .is_signed = true,
      .factor = 0.001,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ALLOW_LONG_PRESS",
      .start_bit = 17,
      .msb  = 17,
      .lsb = 16,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_MALFUNCTION",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RADAR_DIRTY",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 19,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DISTANCE",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MINI_CAR",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_TYPE",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 22,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CANCEL_REQ",
      .start_bit = 24,
      .msb  = 24,
      .lsb = 24,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_CUT_IN",
      .start_bit = 25,
      .msb  = 25,
      .lsb = 25,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PERMIT_BRAKING",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 30,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RELEASE_STANDSTILL",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ITS_CONNECT_LEAD",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_CMD_ALT",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_836[] = {
    {
      .name = "CHECKSUM",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
};
const Signal sigs_869[] = {
    {
      .name = "MAIN_ON",
      .start_bit = 0,
      .msb  = 0,
      .lsb = 0,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CANCEL_BTN",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 1,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_BTN",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RES_BTN",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 3,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_SPEED",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_REQUEST",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 100,
      .offset = -12800.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_DISTANCE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_921[] = {
    {
      .name = "MAIN_ON",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CONTROL_STATE",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DISTANCE_LINES",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 13,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "UI_SET_SPEED",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_951[] = {
    {
      .name = "VSC_DISABLED",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 11,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TC_DISABLED",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_LIGHTS_ACC",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 18,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ENABLED",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ACTIVE",
      .start_bit = 36,
      .msb  = 36,
      .lsb = 36,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_956[] = {
    {
      .name = "SPORT_ON",
      .start_bit = 2,
      .msb  = 2,
      .lsb = 2,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 8,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPORT_GEAR_ON",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 33,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPORT_GEAR",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 36,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ECON_ON",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "B_GEAR_ENGAGED",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 41,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DRIVE_ENGAGED",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1005[] = {
    {
      .name = "REVERSE_CAMERA_GUIDELINES",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 8,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1009[] = {
    {
      .name = "CRUISE_STATE",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAIN_ON",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_SPEED",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1020[] = {
    {
      .name = "LUX_SENSOR",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 59,
      .size = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1041[] = {
    {
      .name = "FCW",
      .start_bit = 4,
      .msb  = 4,
      .lsb = 4,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCS_INDICATOR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 6,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X20",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X10",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCS_OFF",
      .start_bit = 40,
      .msb  = 40,
      .lsb = 40,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCS_SENSITIVITY",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1042[] = {
    {
      .name = "BARRIERS",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_LINE",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 2,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_LINE",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 4,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_STATUS",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 6,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_ALERT",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 8,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_EXIST",
      .start_bit = 10,
      .msb  = 10,
      .lsb = 10,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TWO_BEEPS",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 12,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ADJUSTING_CAMERA",
      .start_bit = 13,
      .msb  = 13,
      .lsb = 13,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_UNAVAILABLE_QUIET",
      .start_bit = 14,
      .msb  = 14,
      .lsb = 14,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_MALFUNCTION",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_UNAVAILABLE",
      .start_bit = 16,
      .msb  = 16,
      .lsb = 16,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_SENSITIVITY",
      .start_bit = 18,
      .msb  = 18,
      .lsb = 17,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_SA_TOGGLE",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 19,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_SPEED_TOO_LOW",
      .start_bit = 21,
      .msb  = 21,
      .lsb = 21,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_ON_MESSAGE",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 30,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REPEATED_BEEPS",
      .start_bit = 32,
      .msb  = 32,
      .lsb = 32,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X01",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LANE_SWAY_TOGGLE",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LANE_SWAY_SENSITIVITY",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 44,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TAKE_CONTROL",
      .start_bit = 46,
      .msb  = 46,
      .lsb = 46,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDA_FRONT_CAMERA_BLOCKED",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 47,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LANE_SWAY_BUZZER",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 49,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LANE_SWAY_FLD",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 51,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LANE_SWAY_WARNING",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 54,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X02",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1043[] = {
    {
      .name = "YEAR",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MONTH",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAY",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HOUR",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MINUTE",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GMTDIFF_MINUTES",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 61,
      .size = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GMTDIFF_HOURS",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 51,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GMT_DIFF",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 55,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SUMMER",
      .start_bit = 60,
      .msb  = 60,
      .lsb = 60,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1083[] = {
    {
      .name = "STATE",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 4,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1161[] = {
    {
      .name = "TSGN1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNHLT1",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 8,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNGRY1",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 10,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPDVAL1",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPLSGN2",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPLSGN1",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 28,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGN2",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNHLT2",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 40,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNGRY2",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 42,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPDVAL2",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SYNCID1",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BZRRQ_A",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BZRRQ_P",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 62,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1162[] = {
    {
      .name = "TSGN3",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNHLT3",
      .start_bit = 9,
      .msb  = 9,
      .lsb = 8,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNGRY3",
      .start_bit = 12,
      .msb  = 12,
      .lsb = 10,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPLSGN4",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPLSGN3",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 28,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGN4",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNHLT4",
      .start_bit = 41,
      .msb  = 41,
      .lsb = 40,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSGNGRY4",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 42,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SGNNUMA",
      .start_bit = 50,
      .msb  = 50,
      .lsb = 48,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SGNNUMP",
      .start_bit = 53,
      .msb  = 53,
      .lsb = 51,
      .size = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DPSGNREQ",
      .start_bit = 54,
      .msb  = 54,
      .lsb = 54,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SYNCID2",
      .start_bit = 59,
      .msb  = 59,
      .lsb = 56,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSRWMSG",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 60,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPDUNT",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 62,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1163[] = {
    {
      .name = "OVSPNTM",
      .start_bit = 1,
      .msb  = 1,
      .lsb = 0,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NTLVLSPD",
      .start_bit = 3,
      .msb  = 3,
      .lsb = 2,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OTSGNNTM",
      .start_bit = 5,
      .msb  = 5,
      .lsb = 4,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSRMSW",
      .start_bit = 6,
      .msb  = 6,
      .lsb = 6,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSREQPD",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 7,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OVSPVALL",
      .start_bit = 11,
      .msb  = 11,
      .lsb = 8,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = -5.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OVSPVALM",
      .start_bit = 19,
      .msb  = 19,
      .lsb = 16,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = -5.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OVSPVALH",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 24,
      .size = 4,
      .is_signed = false,
      .factor = 1,
      .offset = -5.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSRSPU",
      .start_bit = 33,
      .msb  = 33,
      .lsb = 32,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1408[] = {
    {
      .name = "VIN_1",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_2",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_3",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_4",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_5",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_6",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_7",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_8",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1409[] = {
    {
      .name = "VIN_9",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_10",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 8,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_11",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 16,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_12",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 24,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_13",
      .start_bit = 39,
      .msb  = 39,
      .lsb = 32,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_14",
      .start_bit = 47,
      .msb  = 47,
      .lsb = 40,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_15",
      .start_bit = 55,
      .msb  = 55,
      .lsb = 48,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VIN_16",
      .start_bit = 63,
      .msb  = 63,
      .lsb = 56,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1410[] = {
    {
      .name = "VIN_17",
      .start_bit = 7,
      .msb  = 7,
      .lsb = 0,
      .size = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1552[] = {
    {
      .name = "METER_SLIDER_BRIGHTNESS_PCT",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 24,
      .size = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "METER_SLIDER_LOW_BRIGHTNESS",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "METER_SLIDER_DIMMED",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1553[] = {
    {
      .name = "UNITS",
      .start_bit = 26,
      .msb  = 26,
      .lsb = 25,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ODOMETER",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 56,
      .size = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1556[] = {
    {
      .name = "HAZARD_LIGHT",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TURN_SIGNALS",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 28,
      .size = 2,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1568[] = {
    {
      .name = "METER_DIMMED",
      .start_bit = 38,
      .msb  = 38,
      .lsb = 38,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .start_bit = 42,
      .msb  = 42,
      .lsb = 42,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .start_bit = 43,
      .msb  = 43,
      .lsb = 43,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .start_bit = 44,
      .msb  = 44,
      .lsb = 44,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FL",
      .start_bit = 45,
      .msb  = 45,
      .lsb = 45,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PARKING_BRAKE",
      .start_bit = 60,
      .msb  = 60,
      .lsb = 60,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_UNLATCHED",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1570[] = {
    {
      .name = "FRONT_FOG",
      .start_bit = 27,
      .msb  = 27,
      .lsb = 27,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PARKING_LIGHT",
      .start_bit = 28,
      .msb  = 28,
      .lsb = 28,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOW_BEAM",
      .start_bit = 29,
      .msb  = 29,
      .lsb = 29,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM",
      .start_bit = 30,
      .msb  = 30,
      .lsb = 30,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAYTIME_RUNNING_LIGHT",
      .start_bit = 31,
      .msb  = 31,
      .lsb = 31,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HIGH_BEAM",
      .start_bit = 37,
      .msb  = 37,
      .lsb = 37,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1571[] = {
    {
      .name = "DOOR_LOCK_FEEDBACK_LIGHT",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "KEYFOB_LOCKING_FEEDBACK_LIGHT",
      .start_bit = 61,
      .msb  = 61,
      .lsb = 61,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "KEYFOB_UNLOCKING_FEEDBACK_LIGHT",
      .start_bit = 62,
      .msb  = 62,
      .lsb = 62,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1592[] = {
    {
      .name = "LOCK_STATUS_CHANGED",
      .start_bit = 15,
      .msb  = 15,
      .lsb = 15,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOCK_STATUS",
      .start_bit = 20,
      .msb  = 20,
      .lsb = 20,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOCKED_VIA_KEYFOB",
      .start_bit = 23,
      .msb  = 23,
      .lsb = 23,
      .size = 1,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "SECONDARY_STEER_ANGLE",
    .address = 0x23,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_35),
    .sigs = sigs_35,
  },
  {
    .name = "KINEMATICS",
    .address = 0x24,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_36),
    .sigs = sigs_36,
  },
  {
    .name = "STEER_ANGLE_SENSOR",
    .address = 0x25,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_37),
    .sigs = sigs_37,
  },
  {
    .name = "BRAKE",
    .address = 0xA6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_166),
    .sigs = sigs_166,
  },
  {
    .name = "WHEEL_SPEEDS",
    .address = 0xAA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_170),
    .sigs = sigs_170,
  },
  {
    .name = "SPEED",
    .address = 0xB4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_180),
    .sigs = sigs_180,
  },
  {
    .name = "GEAR_PACKET_HYBRID",
    .address = 0x127,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_295),
    .sigs = sigs_295,
  },
  {
    .name = "DSU_SPEED",
    .address = 0x161,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_353),
    .sigs = sigs_353,
  },
  {
    .name = "STEERING_IPAS_COMMA",
    .address = 0x167,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_359),
    .sigs = sigs_359,
  },
  {
    .name = "ENGINE_RPM",
    .address = 0x1C4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_452),
    .sigs = sigs_452,
  },
  {
    .name = "PCM_CRUISE",
    .address = 0x1D2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_466),
    .sigs = sigs_466,
  },
  {
    .name = "PCM_CRUISE_2",
    .address = 0x1D3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_467),
    .sigs = sigs_467,
  },
  {
    .name = "GAS_COMMAND",
    .address = 0x200,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_512),
    .sigs = sigs_512,
  },
  {
    .name = "GAS_SENSOR",
    .address = 0x201,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_513),
    .sigs = sigs_513,
  },
  {
    .name = "BRAKE_MODULE",
    .address = 0x226,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_550),
    .sigs = sigs_550,
  },
  {
    .name = "ACCELEROMETER",
    .address = 0x228,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_552),
    .sigs = sigs_552,
  },
  {
    .name = "BRAKE_2",
    .address = 0x230,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_560),
    .sigs = sigs_560,
  },
  {
    .name = "GAS_PEDAL_HYBRID",
    .address = 0x245,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_581),
    .sigs = sigs_581,
  },
  {
    .name = "STEER_TORQUE_SENSOR",
    .address = 0x260,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_608),
    .sigs = sigs_608,
  },
  {
    .name = "EPS_STATUS",
    .address = 0x262,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_610),
    .sigs = sigs_610,
  },
  {
    .name = "STEERING_IPAS",
    .address = 0x266,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_614),
    .sigs = sigs_614,
  },
  {
    .name = "PRE_COLLISION",
    .address = 0x283,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_643),
    .sigs = sigs_643,
  },
  {
    .name = "GAS_PEDAL",
    .address = 0x2C1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_705),
    .sigs = sigs_705,
  },
  {
    .name = "STEERING_LKA",
    .address = 0x2E4,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_740),
    .sigs = sigs_740,
  },
  {
    .name = "LEAD_INFO",
    .address = 0x2E6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_742),
    .sigs = sigs_742,
  },
  {
    .name = "SDSU",
    .address = 0x2FF,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_767),
    .sigs = sigs_767,
  },
  {
    .name = "ACC_CONTROL",
    .address = 0x343,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_835),
    .sigs = sigs_835,
  },
  {
    .name = "PRE_COLLISION_2",
    .address = 0x344,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_836),
    .sigs = sigs_836,
  },
  {
    .name = "DSU_CRUISE",
    .address = 0x365,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_869),
    .sigs = sigs_869,
  },
  {
    .name = "PCM_CRUISE_SM",
    .address = 0x399,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_921),
    .sigs = sigs_921,
  },
  {
    .name = "ESP_CONTROL",
    .address = 0x3B7,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_951),
    .sigs = sigs_951,
  },
  {
    .name = "GEAR_PACKET",
    .address = 0x3BC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_956),
    .sigs = sigs_956,
  },
  {
    .name = "REVERSE_CAMERA_STATE",
    .address = 0x3ED,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_1005),
    .sigs = sigs_1005,
  },
  {
    .name = "PCM_CRUISE_ALT",
    .address = 0x3F1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1009),
    .sigs = sigs_1009,
  },
  {
    .name = "SOLAR_SENSOR",
    .address = 0x3FC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1020),
    .sigs = sigs_1020,
  },
  {
    .name = "ACC_HUD",
    .address = 0x411,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1041),
    .sigs = sigs_1041,
  },
  {
    .name = "LKAS_HUD",
    .address = 0x412,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1042),
    .sigs = sigs_1042,
  },
  {
    .name = "TIME",
    .address = 0x413,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1043),
    .sigs = sigs_1043,
  },
  {
    .name = "AUTOPARK_STATUS",
    .address = 0x43B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1083),
    .sigs = sigs_1083,
  },
  {
    .name = "RSA1",
    .address = 0x489,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1161),
    .sigs = sigs_1161,
  },
  {
    .name = "RSA2",
    .address = 0x48A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1162),
    .sigs = sigs_1162,
  },
  {
    .name = "RSA3",
    .address = 0x48B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1163),
    .sigs = sigs_1163,
  },
  {
    .name = "VIN_PART_1",
    .address = 0x580,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1408),
    .sigs = sigs_1408,
  },
  {
    .name = "VIN_PART_2",
    .address = 0x581,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1409),
    .sigs = sigs_1409,
  },
  {
    .name = "VIN_PART_3",
    .address = 0x582,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1410),
    .sigs = sigs_1410,
  },
  {
    .name = "BODY_CONTROL_STATE_2",
    .address = 0x610,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1552),
    .sigs = sigs_1552,
  },
  {
    .name = "UI_SETTING",
    .address = 0x611,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1553),
    .sigs = sigs_1553,
  },
  {
    .name = "BLINKERS_STATE",
    .address = 0x614,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1556),
    .sigs = sigs_1556,
  },
  {
    .name = "BODY_CONTROL_STATE",
    .address = 0x620,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1568),
    .sigs = sigs_1568,
  },
  {
    .name = "LIGHT_STALK",
    .address = 0x622,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1570),
    .sigs = sigs_1570,
  },
  {
    .name = "CERTIFICATION_ECU",
    .address = 0x623,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1571),
    .sigs = sigs_1571,
  },
  {
    .name = "DOOR_LOCKS",
    .address = 0x638,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1592),
    .sigs = sigs_1592,
  },
};

const Val vals[] = {
    {
      .name = "GEAR",
      .address = 0x127,
      .def_val = "0 P 1 R 2 N 3 D 4 B",
      .sigs = sigs_295,
    },
    {
      .name = "CRUISE_STATE",
      .address = 0x1D2,
      .def_val = "11 TIMER_3SEC 10 ADAPTIVE_CLICK_DOWN 9 ADAPTIVE_CLICK_UP 8 ADAPTIVE_ENGAGED 7 STANDSTILL 6 NON-ADAPTIVE_CLICK_UP 5 NON-ADAPTIVE_CLICK_DOWN 4 NON-ADAPTIVE_HOLD_DOWN 3 NON-ADAPTIVE_HOLD_UP 2 NON-ADAPTIVE_BEING_ENGAGED 1 NON-ADAPTIVE_ENGAGED 0 OFF",
      .sigs = sigs_466,
    },
    {
      .name = "LOW_SPEED_LOCKOUT",
      .address = 0x1D3,
      .def_val = "2 LOW_SPEED_LOCKED 1 OK",
      .sigs = sigs_467,
    },
    {
      .name = "STATE",
      .address = 0x201,
      .def_val = "5 FAULT_TIMEOUT 4 FAULT_STARTUP 3 FAULT_SCE 2 FAULT_SEND 1 FAULT_BAD_CHECKSUM 0 NO_FAULT",
      .sigs = sigs_513,
    },
    {
      .name = "IPAS_STATE",
      .address = 0x262,
      .def_val = "5 OVERRIDE 3 ENABLED 1 DISABLED",
      .sigs = sigs_610,
    },
    {
      .name = "LKA_STATE",
      .address = 0x262,
      .def_val = "25 TEMPORARY_FAULT 9 TEMPORARY_FAULT2 5 ACTIVE 1 STANDBY",
      .sigs = sigs_610,
    },
    {
      .name = "DIRECTION_CMD",
      .address = 0x266,
      .def_val = "3 RIGHT 2 CENTER 1 LEFT",
      .sigs = sigs_614,
    },
    {
      .name = "STATE",
      .address = 0x266,
      .def_val = "3 ENABLED 1 DISABLED",
      .sigs = sigs_614,
    },
    {
      .name = "STATE",
      .address = 0x283,
      .def_val = "0 NORMAL 1 ADAPTIVE_CRUISE_CONTROL 3 EMERGENCY_BRAKING",
      .sigs = sigs_643,
    },
    {
      .name = "ACC_CUT_IN",
      .address = 0x343,
      .def_val = "1 CUT-IN_DETECTED 0 CLEAR",
      .sigs = sigs_835,
    },
    {
      .name = "ACC_MALFUNCTION",
      .address = 0x343,
      .def_val = "1 FAULTED 0 OK",
      .sigs = sigs_835,
    },
    {
      .name = "ACC_TYPE",
      .address = 0x343,
      .def_val = "2 PERMANENT_LOW_SPEED_LOCKOUT 1 OK",
      .sigs = sigs_835,
    },
    {
      .name = "ALLOW_LONG_PRESS",
      .address = 0x343,
      .def_val = "2 SET_SPEED_INCREASE_BY_5_SPEED_UNITS_REGARDLESS 1 SET_SPEED_INCREASE_BY_1_SPEED_UNIT_ON_SHORT_PRESS,_5_SPEED_UNITS_ON_LONG_PRESS",
      .sigs = sigs_835,
    },
    {
      .name = "CRUISE_CONTROL_STATE",
      .address = 0x399,
      .def_val = "2 DISABLED 11 HOLD 10 HOLD_WAITING_USER_CMD 6 ENABLED 5 FAULTED",
      .sigs = sigs_921,
    },
    {
      .name = "B_GEAR_ENGAGED",
      .address = 0x3BC,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_956,
    },
    {
      .name = "DRIVE_ENGAGED",
      .address = 0x3BC,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_956,
    },
    {
      .name = "ECON_ON",
      .address = 0x3BC,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_956,
    },
    {
      .name = "GEAR",
      .address = 0x3BC,
      .def_val = "0 D 1 S 8 N 16 R 32 P",
      .sigs = sigs_956,
    },
    {
      .name = "SPORT_GEAR",
      .address = 0x3BC,
      .def_val = "1 S1 2 S2 3 S3 4 S4 5 S5 6 S6",
      .sigs = sigs_956,
    },
    {
      .name = "SPORT_GEAR_ON",
      .address = 0x3BC,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_956,
    },
    {
      .name = "SPORT_ON",
      .address = 0x3BC,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_956,
    },
    {
      .name = "REVERSE_CAMERA_GUIDELINES",
      .address = 0x3ED,
      .def_val = "3 NO_GUIDELINES 2 STATIC_GUIDELINES 1 ACTIVE_GUIDELINES",
      .sigs = sigs_1005,
    },
    {
      .name = "PCS_INDICATOR",
      .address = 0x411,
      .def_val = "2 PCS_FAULTED 1 PCS_TURNED_OFF_BY_USER 0 PCS_ENABLED",
      .sigs = sigs_1041,
    },
    {
      .name = "PCS_SENSITIVITY",
      .address = 0x411,
      .def_val = "64 HIGH_SENSITIVITY  128 MID_SENSITIVITY 192 LOW_SENSITIVITY 0 OFF",
      .sigs = sigs_1041,
    },
    {
      .name = "BARRIERS",
      .address = 0x412,
      .def_val = "3 LEFT 2 RIGHT 1 BOTH 0 NONE",
      .sigs = sigs_1042,
    },
    {
      .name = "LANE_SWAY_BUZZER",
      .address = 0x412,
      .def_val = "3 OK 2 BEEP_TWICE 1 BEEP_TWICE 0 OK",
      .sigs = sigs_1042,
    },
    {
      .name = "LANE_SWAY_WARNING",
      .address = 0x412,
      .def_val = "3 OK 2 ORANGE_PLEASE_TAKE_A_BREAK 1 PROMPT_WOULD_YOU_LIKE_TO_TAKE_A_BREAK 0 OK",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_ALERT",
      .address = 0x412,
      .def_val = "3 HOLD_WITH_CONTINUOUS_BEEP 2 LDA_UNAVAILABLE 1 HOLD 0 NONE",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_FRONT_CAMERA_BLOCKED",
      .address = 0x412,
      .def_val = "1 LDA_UNAVAILABLE 0 OK",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_ON_MESSAGE",
      .address = 0x412,
      .def_val = "2 LANE_DEPARTURE_ALERT_TURNED_ON,_STEERING_ASSIST_INACTIVE 1 LANE_DEPARTURE_ALERT_TURNED_ON,_STEERING_ASSIST_ACTIVE 0 CLEAR",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_SA_TOGGLE",
      .address = 0x412,
      .def_val = " 2 STEERING_ASSIST_OFF 1 STEERING_ASSIST_ON",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_SENSITIVITY",
      .address = 0x412,
      .def_val = "2 STANDARD 1 HIGH 0 UNDEFINED",
      .sigs = sigs_1042,
    },
    {
      .name = "LDA_SPEED_TOO_LOW",
      .address = 0x412,
      .def_val = "1 LDA_UNAVAILABLE,_SPEED_TOO_LOW 0 OK",
      .sigs = sigs_1042,
    },
    {
      .name = "LEFT_LINE",
      .address = 0x412,
      .def_val = "3 ORANGE 2 FADED 1 SOLID 0 NONE",
      .sigs = sigs_1042,
    },
    {
      .name = "LKAS_STATUS",
      .address = 0x412,
      .def_val = "1 ON 0 OFF",
      .sigs = sigs_1042,
    },
    {
      .name = "RIGHT_LINE",
      .address = 0x412,
      .def_val = "3 ORANGE 2 FADED 1 SOLID 0 NONE",
      .sigs = sigs_1042,
    },
    {
      .name = "TAKE_CONTROL",
      .address = 0x412,
      .def_val = "1 TAKE_CONTROL 0 OK",
      .sigs = sigs_1042,
    },
    {
      .name = "SPLSGN2",
      .address = 0x489,
      .def_val = "15 CONDITIONAL_BLANK 4 WET_ROAD 5 RAIN 0 NONE",
      .sigs = sigs_1161,
    },
    {
      .name = "TSGN1",
      .address = 0x489,
      .def_val = "1 SPEED_SIGN 0 NONE",
      .sigs = sigs_1161,
    },
    {
      .name = "TSGN2",
      .address = 0x489,
      .def_val = "1 SPEED_SIGN 0 NONE",
      .sigs = sigs_1161,
    },
    {
      .name = "SPLSGN3",
      .address = 0x48A,
      .def_val = "15 CONDITIONAL_BLANK 4 WET_ROAD 5 RAIN 0 NONE",
      .sigs = sigs_1162,
    },
    {
      .name = "TSGN3",
      .address = 0x48A,
      .def_val = "0 NONE 1 SPEED_SIGN 2 0_UNLIMITED 7 UNLIMITED 16 HIGHWAY 17 NO_HIGHWAY 18 MOTORWAY 19 NO_MOTORWAY 20 IN_CITY 21 OUTSIDE_CITY 22 PEDESTRIAN_AREA 23 NO_PEDESTRIAN_AREA 65 NO_OVERTAKING_LEFT 66 NO_OVERTAKING_RIGHT 67 OVERTAKING_ALLOWED_AGAIN 81 NO_RIGHT_TURN 97 STOP 105 YIELD 113 STOP 114 YIELD_US 129 NO_ENTRY 138 NO_ENTRY_TSS2 145 DO_NOT_ENTER",
      .sigs = sigs_1162,
    },
    {
      .name = "METER_SLIDER_DIMMED",
      .address = 0x610,
      .def_val = "1 DIMMED 0 NOT_DIMMED",
      .sigs = sigs_1552,
    },
    {
      .name = "METER_SLIDER_LOW_BRIGHTNESS",
      .address = 0x610,
      .def_val = "1 LOW_BRIGHTNESS_MODE,_FOOTWELL_LIGHTS_OFF 0 NORMAL_MODE,_FOOTWELL_LIGHTS_ON",
      .sigs = sigs_1552,
    },
    {
      .name = "UNITS",
      .address = 0x611,
      .def_val = "1 KM 2 MILES",
      .sigs = sigs_1553,
    },
    {
      .name = "TURN_SIGNALS",
      .address = 0x614,
      .def_val = "3 NONE 2 RIGHT 1 LEFT",
      .sigs = sigs_1556,
    },
    {
      .name = "LOCK_STATUS",
      .address = 0x638,
      .def_val = "0 LOCKED 1 UNLOCKED",
      .sigs = sigs_1592,
    },
};

}

const DBC toyota_tnga_k_pt_generated = {
  .name = "toyota_tnga_k_pt_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(toyota_tnga_k_pt_generated)